### ISSUE TITLE
Keeping track of storage contents

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#106]
We should maintain a list of content for each storage node. We'll be able to:
- know what is there
- migrate pieces to other hosts
- regularly GC by unpinning everything, then pinning only the listed refs
- also: https://ipfs.io/refs/solarnet/storage/castor

Todo:
- [x] create refs-solarnet-storage with files for each host
- all storage users please add their refs to the appropriate files, by host (castor, pollux, sirius)
  - [ ] @davidar 
  - [ ] @diasdavid 
  - [ ] @rht
  - [ ] @mikolalysenko
- we should also include the various refs-to-seed files with e.g. example content
  - [x] https://github.com/ipfs/infrastructure/blob/master/seeding/refs-to-seed
  - [x] this one is probably outdated? https://github.com/protocol/infrastructure/blob/master/seeding/refs-to-seed
  - [ ] any others?
  - [ ] remove them and point to refs-solarnet-storage instead

**Comment by lgierth** [comment]
@jbenet I think you also have stuff on sirius?

**Comment by jbenet** [comment]
Feel free to blow out my content.

**Comment by davidar** [comment]
I only have stuff pinned on the daemon running in my $HOME, and it's basically everything linked from ipfs/archives (duplicated across both storage nodes). I can put them into a list if that would help though.
