### ISSUE TITLE
make security@ipfs.io email group

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#107]
Tentatively, i will add:

- @whyrusleeping
- @diasdavid
- @lgierth
- @jbenet

Are other people willing and interested to be part of this? I will need some ref checks if i don't know you very well personally, because security is a big deal.

**Comment by diasdavid** [comment]
Yes, I'm in :)

**Comment by whyrusleeping** [comment]
@jbenet you might need to perform a background check on @diasdavid,hes kinda shady.

**Comment by diasdavid** [comment]
give me all secrets! :D

**Comment by jbenet** [comment]
don't let that nice trust-worthy smile fool you

![](http://www.ieee-isbc.org/2013/images/speakers/speaker3.png)

**Comment by whyrusleeping** [comment]
looks like hes going to steal my ice cream once hes done with his.

**Comment by diasdavid** [comment]
LOOOOOL

**Comment by lgierth** [comment]
Does security@ipfs.io exist yet?

**Comment by RichardLitt** [comment]
Yes.
