### ISSUE TITLE
windows CI

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#110]
for go-ipfs and such. we need one.

**Comment by harlantwood** [comment]
I believe you can just add `windows` to the OS list in .tavis.yml

**Comment by whyrusleeping** [comment]
i dont think its that easy: https://github.com/travis-ci/travis-ci/issues/216

**Comment by whyrusleeping** [comment]
as well as: https://github.com/travis-ci/travis-ci/issues/2104

**Comment by harlantwood** [comment]
You may be right.  I had just been looking at this yesterday:

https://github.com/Colu-platform/colu-nodejs/blob/master/.travis.yml

But digging in a bit it might not be working as expected : (

**Comment by VictorBjelkholm** [comment]
This is covered in #100 along with a lot of other things as well.
