### ISSUE TITLE
Community Pinning / PinCoop

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#113]
We want to make it easy for the community to pin stuff in order to keep it around. We have [Pinbot](https://github.com/whyrusleeping/pinbot) in #ipfs already, but we want moar!

@VictorBjelkholm has been working on [PinCoop](https://github.com/VictorBjelkholm/pincoop), which is a web app that pins any given hashes on a number of nodes, via their IPFS API. One problem with this push-based approach is that the API needs to be opened up, in particular `/id` and `/pin/{add,rm,ls}` endpoints.

There is another idea around a pull-based approach, where users submit hashes to a pinlist, which participating nodes pull and apply at their convenience. The pinlist could live within https://ipfs.io/refs (see [ipfs/refs](https://github.com/ipfs/refs)), and there could as well be multiple different pinlists.

**Comment by VictorBjelkholm** [comment]
Nice! PinCoop was supposed to be a community run service where people can "donate" pinning of content that the community would like to stay up forever. Early on, I was thinking about the benefits of a push based model which is minimal setup from the node-owners point of view, and speed of getting an overview of the network. But quickly after starting prototyping, I starting realizing the downsides. Security and complexity being the top ones.

So right now, I'm working on a much simpler pull-based model, which is easier to develop and hopefully will be easy to setup as well.

Looks a bit like this atm:
<img width="686" alt="screen shot 2015-11-11 at 15 03 04" src="https://cloud.githubusercontent.com/assets/459764/11092667/56107570-8885-11e5-9cc4-0a775f3cadb1.png">

My main point with this is two things. Provide a GUI to easy pin content that you've added elsewhere. Second point being to provide an API to pin things that you've (or your user) have added through your service.

All feedback is good feedback so speak your mind please :)

**Comment by davidar** [comment]
:+1:

@VictorBjelkholm have I already discussed the possibly of splitting large datasets across multiple nodes with you?

**Comment by VictorBjelkholm** [comment]
@davidar I don't think so. I know it's something we want but I haven't give it a thought yet. If you have any thoughts around this, please explain more so I can understand it :)

**Comment by jbenet** [comment]
Let's please make [ipfs-cluster](https://github.com/ipfs/notes/issues/58)
