### ISSUE TITLE
pinbot fails

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#117]
pinbot has been failing over small things

**Comment by lgierth** [comment]
Yeah that's likely because of pluto running dev0.4.0

- can't access the stuff that's to be pinned
- has an incompatible api version?

**Comment by lgierth** [comment]
I already have that in my sprint todos, I guess I'll just exclude pluto from pinbot

**Comment by jbenet** [comment]
Sgtm

**Comment by lgierth** [comment]
fixed in #120
