### ISSUE TITLE
Gitter / IRC bridge down

### ISSUE THREAD

**Issue by harlantwood** [ipfs/infrastructure#118]
Gitter https://gitter.im/ipfs/ipfs was two-way bridging to #ipfs IRC until Nov 8.  Can we get it back?  It was a great experience, at least for me.

**Comment by jbenet** [comment]
@awrelll

**Comment by awrelll** [comment]
Sorry for the downtime, docker just crashed. The bridge is up now !

**Comment by harlantwood** [comment]
Awesome!

**Comment by jbenet** [comment]
Maybe We should have a reliable way to detect those failures

**Comment by harlantwood** [comment]
@awrelll the gitter bridge is down again, since about 2 days ago.

@lgierth mentioned that we run our IPFS docker container with restart=true ... maybe we could do something similar for gitter docker container?  (I am docker newb, so just pinging the people who know things here :)
