### ISSUE TITLE
Github Bridge

### ISSUE THREAD

**Issue by harlantwood** [ipfs/infrastructure#119]
Combining discussions about:

- deploys triggered by a git commit from a github webhook:  https://github.com/ipfs/website/issues/17#issuecomment-156660645
- oauth gateway to allow users to github auth to use the API: https://github.com/ipfs/ci-status/issues/6#issue-117752274

I suggest we create a new repo `ipfs/git-bridge` which will handle both of these tasks, and possibly more github bridges as needs arise.

**Comment by harlantwood** [comment]
Remembering... don't we have something that uses github auth already?  a bot / pinbot perhaps?  or maybe @jbenet just mentioned this as an idea for the next (hubot) pinbot?

**Comment by davidar** [comment]
:+1: would also be great if it could set appropriate DNS records so the mirror could be accessed via `<github-username>.gh.ipfs.io`

**Comment by harlantwood** [comment]
hm... @davidar are you thinking of an IPFS mirror of github repos?  while that is clearly awesome, it's not what I'm proposing here, I'm proposing a server which handles the sever side of oauth (log in with github) and the server side of githooks, eg a server which can do builds/deploys on a given commit.

I edited the original post in this thread for clarity as well.

**Comment by harlantwood** [comment]
Hm, I originally suggested the repo be ipfs/git-bridge, but `ipfs/github-bridge` is more descriptive and clear.

**Comment by davidar** [comment]
@harlantwood Oh, sorry, I though you were talking about a webhook to deploy github-pages sites to IPFS.

**Comment by harlantwood** [comment]
Closing in favor of https://github.com/ipfs/infrastructure/issues/137
