### ISSUE TITLE
webtorrent tracker

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#121]
Was talking to @feross and it would help if we ran a couple of instances of https://github.com/feross/bittorrent-tracker to help out the webtorrent network (they have a lot of load today!) 
- could we maybe put two in some of our larger machines?
- maybe something like:
  
  ```
  webtorrent-tracker1.ipfs.io
  webtorrent-tracker2.ipfs.io
  ```
  
  or something?

@feross said:

> just run `npm install bittorrent-tracker`, then run `bittorrent-tracker --ws`
> the `--ws` option will ensure that you're only running a tracker for webrtc peers (far less load)

maybe we can dockerize it for easyness

**Comment by jbenet** [comment]
@feross preferred node/npm version?

**Comment by jbenet** [comment]
@lgierth any machines preferred?

**Comment by feross** [comment]
Node 4, since it's LTS. Any npm version is fine.

Thanks guys – this is immensely useful!

**Comment by lgierth** [comment]
A docker image would be great, then we can just copy-paste a bit.

What kind of load do you have -- bandwidth, CPU? How much storage will you need, is it in the 1G, 10G, or 100G range?

Anyhow, castor has the most headroom in both CPU and storage. If bandwidth is the bottleneck, I'd rather put it on deimos (currently only Pinbot) and one of the bigger gateway nodes.

**Comment by jbenet** [comment]
i think it's mostly bandwidth?

**Comment by lgierth** [comment]
> A docker image would be great, then we can just copy-paste a bit.

If there is none yet, we can quickly wind up one

**Comment by jbenet** [comment]
Yep. i think we want `FROM node:onbuild` or `FROM node:slim` -- https://hub.docker.com/_/node/

Oh, we should make a Docker base image that includes multihash tool or ipget to retrieve things + verify hashes.

**Comment by jbenet** [comment]
or maybe that's v2. v1:

```Dockerfile
FROM node:4.2.2-onbuild
npm install bittorrent-tracker
CMD bittorrent-tracker
```
or something?

**Comment by feross** [comment]
It's not much in the way of storage. The tracker just coordinates peers by relaying WebRTC signaling data (small JSON payloads). It's just lots of connections.

**Comment by lgierth** [comment]
I'd rather build from a specific revision, so that we know what's running without jumping through hoops. We'll have to redeploy anyhow for updates.

> It's not much in the way of storage. The tracker just coordinates peers by relaying WebRTC signaling data (small JSON payloads). It's just lots of connections.

Great!

**Comment by jbenet** [comment]
@lgierth sounds good, have an example of your fav install way within docker?

**Comment by jbenet** [comment]
Actually, we can rely on npm to version lock:

```Dockerfile
FROM node:4.2.2-onbuild
npm install bittorrent-tracker@6.0.7
CMD ["node_modules/.bin/bittorrent-tracker", "--ws"]
```
if npm is hosed, installing the deps is going to hose us anyway. can use npm shrinkwrap, but im not well versed in the nuances :)

**Comment by jbenet** [comment]
Seems like "the way to do it" in docker node land is to add a file like:

```
> cat bittorrent-tracker/Dockerfile
FROM node:4.2.2-onbuild
CMD ["./bin/cli.js", "--ws"]
```
- `CMD` line because we want to override default to force `--ws`
- `./bin/cmd.js` because https://github.com/feross/bittorrent-tracker/blob/master/package.json#L11

The node image knows to copy all the stuff and npm install.

Then:
```sh
> docker build -t webtorrent-tracker .
... [snip]
Successfully built 0022175c714f
> docker run -p 8686:8000 0022175c714f
WebSocket tracker: ws://localhost:8000
```
- chose `8686` but could be whatever

It's theoretically live at: 
```
deimos.i.ipfs.io:8686
```
- @feross best way to test?

**Comment by lgierth** [comment]
SGTM! :)

I think it's okay to not codify this in infrastructure.git as it seems to be just `docker run`. Make sure to set restart_policy=always though.

**Comment by feross** [comment]
@jbenet Looks like it's working!

The next step is to settle on a more "permanent" url so we can get an SSL cert. Otherwise SSL sites like https://instant.io/ and https://webtorrent.io/ can't open connections to the server.

It's a bit annoying to get a cert, but it'll make the tracker waaaaaay more useful.

You guys rock!

**Comment by jbenet** [comment]
@feross would a self-signed cert work? if not, we can grab one from https://letsencrypt.org in a few days...

@lgierth we probably should've gotten a wildcard cert for `ipfs.io`

**Comment by feross** [comment]
Self-signed won't work since that will trigger warnings in the browser. A wildcard is really the way to go if you can afford it.

**Comment by davidar** [comment]
Let's Encrypt goes public tomorrow ;)

**Comment by feross** [comment]
Nice - let's do it. Then I'll add it to the list of default trackers.

**Comment by lgierth** [comment]
Is that webtorrent tracker still running? we have a wildcard cert for *.ipfs.io now, so we can do e.g. webtorrent.ipfs.io.

@feross please reopen if you still have a need

**Comment by feross** [comment]
@lgierth Yes, this would be most excellent! Let's do it -- if you're still up for it.

(I can't re-open the issue since it was closed by a repo owner.)

**Comment by lgierth** [comment]
Sorry, I just didn't have the bandwidth to dive into this, and it's unlikely that I'll be able to anytime soon. @feross if you like I can get a machine for you to operate, though.

**Comment by feross** [comment]
No worries, there are several community-run webtorrent trackers already. No need to fret about it.

**Comment by lgierth** [comment]
Thanks :)
