### ISSUE TITLE
Hardware for private keys

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#122]
We should setup core devs with some hardware for private keys. yubikeys seem to be in vogue. what are other best options?

**Comment by whyrusleeping** [comment]
![](http://i.imgur.com/GZKFN05.jpg)

Yubikeys are great. Doesnt leave my person, and all my accounts are two factor authed. 

I also make sure all my private keys are encrypted, and ssh-agent flushes them every ten minutes. My hard drives for all my development devices are also encrypted.

I'd actually like it if everyone with go-ipfs write access was required to have 2FA on their account.

**Comment by lgierth** [comment]
I got a Yubikey a while ago, just haven't gotten to setting it up yet. All of the above SGTM.

**Comment by lgierth** [comment]
I could order one for everyone of us coming to 32C3, @jbenet do you need one too?

**Comment by lgierth** [comment]
also @diasdavid @kyledrake @mappum @cryptix?

**Comment by diasdavid** [comment]
I've one somewhere (from 2011), I wouldn't mind having a new and shine one :)

**Comment by jbenet** [comment]
@lgierth yeah let's

**Comment by lgierth** [comment]
@ipfs I'll order in three days -- it's one so far for @diasdavid 

@jbenet I can order one for you too if you mail me an address

@mappum @cryptix @digniedquire @RichardLitt  what about you?

**Comment by Dignifiedquire** [comment]
Yes please :)

**Comment by cryptix** [comment]
I'm in!

**Comment by RichardLitt** [comment]
in!

**Comment by mappum** [comment]
Sure, a Yubikey would be useful! :smile:

**Comment by lgierth** [comment]
Orders places -- @jbenet and @RichardLitt get theirs delivered home, I'll have the other 4 with me at 32c3

**Comment by RichardLitt** [comment]
Thanks!

**Comment by lgierth** [comment]
I've receive a little package of yubikeys, @RichardLitt @jbenet got yours too?

**Comment by RichardLitt** [comment]
Yep!

**Comment by jbenet** [comment]
Yes thank you! :D

**Comment by cryptix** [comment]
Can't wait :]

**Comment by lgierth** [comment]
@mappum I didn't realize you wouldn't come to 32c3 so I have your yubikey with me here :/

**Comment by lgierth** [comment]
@cryptix let's do it! Totally forgot about it the past days, but I have the yubikeys with me

**Comment by lgierth** [comment]
> @mappum I didn't realize you wouldn't come to 32c3 so I have your yubikey with me here

gave it to whyrusleeping :)
