### ISSUE TITLE
CiteSeerX instance

### ISSUE THREAD

**Issue by davidar** [ipfs/infrastructure#123]
Apparently, the best way forward regarding mirroring CSX's PDF collection is to setup our own [CSX instance](https://github.com/SeerLabs/CiteSeerX), and then mirror that to IPFS. They'll give us a copy of their data to get started, but we'll be responsible for handling DMCA takedowns, etc.

@lgierth Thoughts?

Cc: @jbenet

**Comment by davidar** [comment]
@mekarpeles Is this something @ArchiveLabs could do?

**Comment by mekarpeles** [comment]
For the public access stuff, I believe so.

**Comment by lgierth** [comment]
Sorry for letting you wait so long -- CSX [looks pretty heavy](https://github.com/SeerLabs/CiteSeerX/blob/master/doc/cxm.pdf), can you set it up on pollux? Or on another separate host. How much storage do you think that'll need?

**Comment by davidar** [comment]
@lgierth I think the database is ~4TB compressed, plus whatever extra overhead CSX requires.

@cleegiles Help? :)

**Comment by cleegiles** [comment]
It's a bit larger, more like 5T. But most of this are the compressed PDFs - 6.8M

The database, xml and extracted text is much smaller - compressed respectively 20G, 30G, 100G

**Comment by davidar** [comment]
@lgierth [Here](https://hub.docker.com/r/davidar/docker-csx/)'s a docker image with most of the dependencies required for CiteSeerX. I'm having trouble getting mysqld to start though, would you mind taking a look?

**Comment by cleegiles** [comment]
It would be best to take this up here:

> https://github.com/SeerLabs/CiteSeerX/

**Comment by lgierth** [comment]
@davidar do you still wanna work on this? We could just get you a host with a big disk and you're root
