### ISSUE TITLE
Prometheus exporter for IPFS API

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#129]
We're about to rip prometheus out of go-ipfs, and need something to poll the API for this info.

Examples:

- `ipfs swarm peers | wc -l`
- `:5001/debug/pprof`

**Comment by jbenet** [comment]
too big?

**Comment by lgierth** [comment]
While factoring out go-libp2p it became clear that the current integration isn't waterproof, i.e. go-libp2p would be depending on the prometheus client code. I didn't wanna justify this kind of bloat right at the birth of libp2p, and @whyrusleeping was happy enough to rip it out.

**Comment by jbenet** [comment]
Between no metrics and bloat we should be choosing bloat right now. gx should make it not a problem to depend on this. gx should only be downloading source code, so it should be pretty light. (and yes Go binaries are bloated in general)

**Comment by jbenet** [comment]
We should be adding more metrics, not removing them. I'm happy with whatever, but we shouldn't have a long interruption in metrics-- which is likely to happen if we don't make this an atomic swap (i.e. have something to replace it before removing it)

**Comment by lgierth** [comment]
We have the proper IpfsCollector in go-ipfs now, which so far collects `p2p_peers_total` -- more possible metrics are:

  - ipfs_p2p_peers -- number of peers
    - by transport, e.g. `transport=/ip6/udp/utp`
  - ipfs_gateway_request_inflight -- active gateway requests
  - ipfs_api_request_inflight -- active API requests
  - ipfs_repo_size -- disk space used by fs-repo
  - ipfs_bitswap_wants -- number of wants
  - ipfs_bitswap_bytes_rx -- incoming bytes counter
  - ipfs_bitswap_bytes_tx -- outgoing bytes counter
