### ISSUE TITLE
Deprecating sirius and castor hosts

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#134]
cc @davidar @diasdavid 

We wanna get rid of sirius and castor. All new downloads should go to biham.i.ipfs.io instead, which has some 17 TB storage and won't go away as fast as castor (promised).

### sirius

- I disabled logins on sirius (it's full anyhow)
- I started copying its /home to biham (in a root screen)
- So far it's averaging at 1 MB/s (might take 2 weeks to finish)

### castor

@davidar sorry to bother you with this again :) could you move the gutenberg download to biham too? You can move it yourself, or let me move it with the other homes, then resume.

**Comment by lgierth** [comment]
I'd like to get rid of castor before christmas, so that we don't have to renew it once more (it's paid until dec 28th)

**Comment by jbenet** [comment]
bie sirius + castr:

![](https://media.giphy.com/media/rn79UlSTDfDlS/giphy.gif)

**Comment by diasdavid** [comment]
@lgierth will you move Castor repo entirely or will it be a new node? I need to update stuff on registry-mirror so that it doesn't point to a dead star anymore

**Comment by lgierth** [comment]
@diasdavid we can have biham reuse castor's peerid

**Comment by diasdavid** [comment]
@lgierth that would be sweet! If you use Castor IPFS Repo, than I just need to change the multiaddr on registry-mirror

**Comment by jbenet** [comment]
@lgierth is the stuff from sirius moved? lmk when i can shut it down

**Comment by lgierth** [comment]
Yep sirius is indeed good to be canceled -- I'm powering it off now and taking it out of monitoring.

**Comment by lgierth** [comment]
> Yep sirius is indeed good to be canceled -- I'm powering it off now and taking it out of monitoring.

Okay @jbenet go ahead cancelling it

**Comment by jbenet** [comment]
Issued cancellation. i will close when it's done

**Comment by lgierth** [comment]
> Issued cancellation. i will close when it's done

ping @jbenet

**Comment by lgierth** [comment]
ping @jbenet

**Comment by jbenet** [comment]
Afaik this is cancelled. Will double check.
