### ISSUE TITLE
Wildcard SSL cert for ipfs.io

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#138]
Blocks #101 and #121

**Comment by lgierth** [comment]
We can get a 2-year cert from StartSSL for $60: https://startssl.com/?app=39

**Comment by jbenet** [comment]
SGTM

**Comment by jbenet** [comment]
(unless we want to use letsencrypt for all of them-- i hear can use cli to
request them)

**Comment by cloutier** [comment]
@jbenet Letsencrypt works well if you already know all the subdomains you are going to use. It might get messy if you generate subdomain on the fly à la wordpress.com.

**Comment by lgierth** [comment]
Wildcard certs aren't part of their spec and it's not clear if they ever will.

> It might get messy if you generate subdomain on the fly à la wordpress.com

It *will* get messy ;)

**Comment by lgierth** [comment]
done
