### ISSUE TITLE
gateway (ipfs.io/ipfs) will pick randomly between 0.3 and 0.4

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#146]
i _think_ that right now, because "ipfs.io" yields one of the ips, which may be running 0.3 or may be running 0.4, the "ipfs.io" service is composed of 2 sets of servers that don't talk to each other. so if you access an "ipfs.io" link, the node your browser hits may or may not be able to resolve it.

**Comment by jbenet** [comment]
yep @lgierth just confirmed this

**Comment by jbenet** [comment]
Hm maybe not -- 

```
> dig ipfs.io
ipfs.io.		83	IN	A	128.199.219.111
ipfs.io.		83	IN	A	178.62.158.247
ipfs.io.		83	IN	A	178.62.61.185
ipfs.io.		83	IN	A	104.236.151.122
ipfs.io.		83	IN	A	104.236.76.40
```

`http://$ip/version` shows this for all

```
Commit: fbb607d
Client Version: go-ipfs/0.3.11-dev
Protocol Version: ipfs/0.1.0
```

**Comment by jbenet** [comment]
aHA! 

```
> dig gateway.ipfs.io
gateway.ipfs.io.	109	IN	A	104.236.179.241
gateway.ipfs.io.	109	IN	A	104.236.176.52
gateway.ipfs.io.	109	IN	A	162.243.248.213
gateway.ipfs.io.	109	IN	A	178.62.158.247
gateway.ipfs.io.	109	IN	A	178.62.61.185
gateway.ipfs.io.	109	IN	A	104.236.76.40
```

- http://104.236.179.241/version - 0.4.0
- http://104.236.176.52/version - 0.4.0
- http://162.243.248.213/version - 0.3.11
- http://178.62.158.247/version - 0.3.11
- http://178.62.61.185/version - 0.3.11
- http://104.236.76.40/version - 0.3.11

@lgierth o/

**Comment by lgierth** [comment]
Fixed o/

```sh
$ dig +short gateway.ipfs.io
104.236.76.40
178.62.158.247
178.62.61.185
104.236.151.122
128.199.219.111
```
