### ISSUE TITLE
Duplicating HTTP proxy

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#147]
@whyrusleeping 

I have no clue of a better name for this.
 
A little proxy tool that sits between nginx and two ipfs daemons' gateways

- proxies each request to both of the backends (v03x + v04x), simultaneously
- we can't do this serially, because we can't reasonably time out and try the next backend
- the only thing we *can* reliably say is when a request is successful
- requests and responses should not get buffered (RAM usage!)

- first successful response is sent to the client
- after successful response, request/response to other backend is aborted/discarded
- first error is discarded
- second error is sent to the client

**Comment by ralphtheninja** [comment]
> proxies each request to both of the backends (v03x + v04x), simultaneously

:+1: 

Can we make `pinbot` use nginx so we can pin on both v03 and v04 at the same time?

**Comment by ralphtheninja** [comment]
Maybe nginx isn't the right way for pinbot, but it would be nice to be able to pin on both versions somehow.

**Comment by lgierth** [comment]
Yes we'll take care of that too this week

**Comment by ralphtheninja** [comment]
:rocket:

**Comment by lgierth** [comment]
We have multireq running fine now https://github.com/whyrusleeping/multireq
