### ISSUE TITLE
Add column to Waffle for the current sprint

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/infrastructure#15]
@hosh You have the most knowledge on this.

Some column names for the current sprint:
* Sprint
* Ready

For the backlog column:
* Keep the current name?

**Comment by jbenet** [comment]
:+1: for Sprint.

**Comment by dylanPowers** [comment]
I've added in the sprint column to waffle.io/ipfs/ipfs. How do you like it @jbenet? We're starting to get a lot of columns, but I think it's still manageable.

**Comment by jbenet** [comment]
@dylanPowers that looks good to me! maybe we should make it a habit to go through it every sprint. let's do it next week
