### ISSUE TITLE
Automated builds of go-ipfs on Docker Hub

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#152]
@Luzifer I can't figure out how to add an automated build, *without* giving it access to all private repos of myself and the organizations I'm a member in.

Any idea?

**Comment by lgierth** [comment]
If I use the restricted version, it'll only accept public repos in my own Github account, but not e.g. ipfs/go-ipfs

**Comment by Luzifer** [comment]
Hmm I guess I gave them those permissions… Maybe there is a chance to limit permissions to only public repos and include only one organization? With the new permissions this should be possible but I think all orgs need already to be converted to the new permission model…

**Comment by lgierth** [comment]
I went with giving permission, creating the automated build, then revoking permission again. Let's see how it goes :)
