### ISSUE TITLE
Double gzip compression of files

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#163]
Example: https://dist.ipfs.io/go-ipfs/v0.4.2/go-ipfs_v0.4.2_linux-amd64.tar.gz or https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.2/go-ipfs_v0.4.2_linux-amd64.tar.gz

Results in: https://gist.github.com/Kubuxu/7a5a8ed0454ee7113c543117dbfaf683

**Comment by lgierth** [comment]
This is a an issue for distributions.git -- not sure what the issue is. dist's build-go.sh looks okay, and I using `tar -xf` or `gzip -d` for uncompression works fine.

**Comment by lgierth** [comment]
And I don't get your double zcat -- after the first zcat, it's a tarball.

**Comment by Kubuxu** [comment]
It happens only with browser.

Local gateways are not affected only the global ones.

**Comment by lgierth** [comment]
I just got this with https://ipfs.io/ipns/dist.ipfs.io/fs-repo-migrations/v1.1.0/fs-repo-migrations_v1.1.0_linux-amd64.tar.gz

**Comment by lgierth** [comment]
Disabled gzip compression in 803b9790c6e7a4426748d20fbcf7fb6411d6a683

> Firefox has this bug with Content-Encoding: gzip, and .tar.gz files.
> It won't gunzip anything, and leave you with a double-gzipped tarball.
>
> Our new website is smaller than the old one,
> so I think it's okay to remove gzip compression for now.
