### ISSUE TITLE
ipfsbot should use notice instead of channels messages

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#164]
I don't know if it is a good place for it but there is a request:
ipfsbot on #ipfs should use notices instead of messages to reduce noise and pings to people.

**Comment by lgierth** [comment]
Yeah agreed, those highlights are annoying. It seems to be a matter of setting Notice=true in https://github.com/ipfs/go-ipfs/settings/hooks

**Comment by lgierth** [comment]
@diasdavid @dignifiedquire maybe same for the js-* projects?

**Comment by lgierth** [comment]
Or we can just move it to a separate channel called #ipfs-commits or so.

**Comment by Kubuxu** [comment]
I think notice instead of channel messages are good enough, at least for now.

**Comment by dignifiedquire** [comment]
Agreed, should be for all the projects. Also if we actually use it we should activate it on all major projects not just on like 3

**Comment by diasdavid** [comment]
Agree with al the above. I would even dare to say that it would to have a page that shows stream of all the activity :)

**Comment by Kubuxu** [comment]
@whyrusleeping can you change that option?

**Comment by whyrusleeping** [comment]
I don't know where those options are to be honest

**Comment by lgierth** [comment]
Closing since the bot has been disabled
