### ISSUE TITLE
CORS is not enabled on gateways

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#166]
Following options should be set to allow CORS requests on ipfs.io: https://github.com/ipfs/go-ipfs/issues/2239#issuecomment-205063851

I will work on a patch to add those options to defaults in go-ipfs but it will require changes in already setup configs.

**Comment by Kubuxu** [comment]
Test here: http://test-cors.org/#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fipfs.io%2Fipfs%2FQmNUFNQXWVzbhePhj6bscW6TPu5azraCpbejbNY9zyfFjo%2F&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

**Comment by lgierth** [comment]
Looks good now
