### ISSUE TITLE
biham: No space left on device

### ISSUE THREAD

**Issue by davidar** [ipfs/infrastructure#167]
According to `df` biham still has 1.7T of free space, but I'm getting `IOError: [Errno 28] No space left on device` errors when trying to create files.

@lgierth Help? :)

**Comment by whyrusleeping** [comment]
i'd unmount it and fsck it.... Then delete it all and reformat it to a sane filesystem like btrfs :stuck_out_tongue:

**Comment by Kubuxu** [comment]
inodes?

**Comment by davidar** [comment]
@Kubuxu what about them?

**Comment by davidar** [comment]
It seems I'd managed to consume about half the available inodes with all the OSM tiles (oops!). I've cleaned that up now, so the immediate problem has been resolved, but is the ipfs repo likely to trigger a similar issue at some point in the future due to all the small files in the flatfs (@whyrusleeping)?

**Comment by Kubuxu** [comment]
Yeah it might be a problem. There are two solutions: @lgierth can migrate the storage to inote-free filesystem or we can write better flatfs that would hold multiple blocks in one file.

**Comment by lgierth** [comment]
@whyrusleeping is gonna take a look at rebuilding the other big storage host (nihal)

**Comment by davidar** [comment]
@lgierth biham is now full in the traditional sense :/

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/md3         17T   16T     0 100% /mnt/data
```

**Comment by lgierth** [comment]
I've cleaned up 6T or so by removing @diasdavid's npm registry stuff a while ago
