### ISSUE TITLE
HEAD requests broken on ipfs.io

### ISSUE THREAD

**Issue by theoreticalbts** [ipfs/infrastructure#169]
Try this:

    curl --head https://ipfs.io/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme

Response is 200 OK for local go-ipfs, but ipfs.io gives 503 Service Unavailable -- something in the ipfs.io setup breaks HEAD requests.  Related: #159

Edit:  ipfs.io also 503's for plain HTTP.

**Comment by lgierth** [comment]
Thanks @theoreticalbts -- this was fixed in April already but somehow I forgot to deploy the fix :S

Fixed in 8f0b79a and whyrusleeping/multireq#9

**Comment by lgierth** [comment]
Duplicate of #159 :)
