### ISSUE TITLE
Add ipfs/api to the repo list

### ISSUE THREAD

**Issue by dylanPowers** [ipfs/infrastructure#17]
Add https://github.com/ipfs/api
- [ ] Waffle.io
- [ ] ipfs/ipfs/project-directory

**Comment by dylanPowers** [comment]
@jbenet I want to hold off on this until the repo actually has content

**Comment by jbenet** [comment]
sgtm

**Comment by RichardLitt** [comment]
@jbenet Do we still use waffle.io for anything?

**Comment by jbenet** [comment]
i think some people view it.

i personally don't.

**Comment by whyrusleeping** [comment]
I dont
