### ISSUE TITLE
Enabling bloom filter

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#174]
After https://github.com/ipfs/go-ipfs/commit/8fbbd7f7112a80552c973db31ed67b4095bbb65e bloom filter has to be explicitly enabled.

We want to do that on our machines.

Depending on size of storage host I recommend: ~50k blocks 4194304 bits (512KiB) and in case of bigger storages few MiB (in bits).

**Comment by lgierth** [comment]
PRs welcome :) https://github.com/ipfs/infrastructure/blob/master/ipfs/config.tpl

**Comment by Kubuxu** [comment]
I will do it after https://github.com/ipfs/go-ipfs/pull/2971 is merged and we have few more gateways deployed with it.

It is as simple as setting one variable as the binding for a setting is already in.

**Comment by hsanjuan** [comment]
The recommended size for the bloom filter should be mentioned in the ipfs docs. I stumbled upon this looking for that information.
