### ISSUE TITLE
Notes from infrastructure handoff meeting

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#178]
@lgierth is going on vacation so I will be taking over as the primary person in charge of the ipfs infrastructure with @Kubuxu acting as a backup in the cases where I might be unavailable.

Here are the notes from the meeting we had:
# IPFS Infrastructure Management
## Setup
1. clone infra repo (https://github.com/ipfs/infrastructure)
2. install dependencies (comment at the top of ./provsn)
   - gnu parallel, bash, jq, git, etc.
3. need secrets
   - currently this process is manual
   - switch to secrets manager in future (hashicorp vault?)
   - put them in ./secrets
### ansible
- cd ansible && make deps
## Deploying New Changes
- provsn deploy [optional array of node names]
  - build and deploy current configuration to nodes
  - [ ] should report success (currently doesnt)
  - [ ] add verbose flag
  - troubleshooting:
    - set PROVSN_TRACE=1 (causes LOTS of noise)
  - [ ] fix ansible-playbook gateway.yml without secrets
  - [ ] XXX rekey cjdns
  - [ ] put listen fc00 back into place
- provsn build
  - just does the build but doesnt push changes live
## DMCA Blocking
- open ansible/roles/ipfs_gateway/templates/nginx_ipfs_gateway.conf.j2
- add rule for hash in question like:

```
    location ~ "^/ipfs/QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n" {
        return 451;
    }
```
- `source venv/bin/activate`
- `ansible-playbook gateway.yml`
## Deploying dnslink websites
- use meldium to get acccess to digitalOcean
- change relevant TXT record dnslink value
  - example: `TXT _dnslink dnslink=/ipfs/QmUskK3M9ANENsAb5YVC3Lc2TiUBcLqL8KpKUsRHKFGqKz`
  - for foo.ipfs.io, TXT record is _dnslink.foo.ipfs.io
- If its a new record, add CNAME to gateway.ipfs.io
## ssh access to gateways
- add new key in base/env.sh to all_ssh_keys array
- `provsn deploy`
## running a migration

NOTE: daemon will be offline during migration
## direct access to container logs
# 1. grab container-id

root@earth:~# docker ps
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS              PORTS                      NAMES
eae427ee13bf        mtail:a54f860fe8b14440320014ed608e438a790f19ac   "/usr/local/bin/mtail"   4 minutes ago       Up 4 minutes        127.0.0.1:3903->3903/tcp   mtail
c0846895f92c        ipfs:566c08e                                     "/usr/local/bin/start"   6 days ago          Up 3 hours                                     ipfs
619bc76884dc        nginx:1.10.1                                     "nginx -g 'daemon off"   7 weeks ago         Up 8 hours                                     nginx
# 2. grab log from /var/lib/docker/containers/$containerID/$containerID-json.log

root@earth:~# tail -f /var/lib/docker/containers/c0846895f92c3a39d6ced41329ff58e1b7e80e56d9254d4a392603fc759138ad/c0846895f92c3a39d6ced41329ff58e1b7e80e56d9254d4a392603fc759138ad-json.log
## General Gateway IPFS Info
- ipfs daemon is run in a docker container with the repo mounted from /ipfs/ipfs_master/repo
- docker will automatically restart the ipfs daemon if it crashes or stops for any reason

**Comment by RichardLitt** [comment]
Is this actionable? Could probably be closed, now that it is logged here. Or we could turn this into a README.
