### ISSUE TITLE
nightly go-ipfs builds on distributions page 

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#180]
I think we're at the point where we should start thinking about setting up automated nightly builds, and pushing them to dists. Teamcity can likely do this for us, at least up to the point where we need to publish the new page.

Some random related thoughts:
- need to make sure we unpin old nightly versions to not run out of gateway space
- should we use teamcity? what other options are out there for this?
- should add link to 'nightlies' on front page of dist to advertise we have them (RCs too!)
- should have manual verification at first. don't hand the keys over to the robots!

cc @lgierth @chriscool @Kubuxu

**Comment by whyrusleeping** [comment]
ref https://github.com/ipfs/go-ipfs/issues/2828#issuecomment-242221987

**Comment by whyrusleeping** [comment]
Also: https://github.com/ipfs/distributions/issues/77

**Comment by lgierth** [comment]
The build/add/pin and move-old-pins-to-archive-host steps are almost exactly what all of the websites and mirrorings need too.

:arrow_right: ipfs-pages

**Comment by pataquets** [comment]
If given a choice, I would ask it as Docker images, too.
[Automated Builds](https://docs.docker.com/docker-hub/builds/) on Docker Hub would be helpful, since it can automatically generate image tags based on each branch.
Just my 2c.

**Comment by Kubuxu** [comment]
docker builds are available for every commit hash on master from https://hub.docker.com/r/ipfs/go-ipfs/

**Comment by pataquets** [comment]
Thanks, @Kubuxu. For nightlies I was also thinking in feature branches, too. Not just master, since some experiments live in other branches. Sorry for the confusion.

**Comment by whyrusleeping** [comment]
@pataquets agreed, having nightly builds for feature branches (feat/datastore-configs for example) would be a great thing to have.

**Comment by Kubuxu** [comment]
I think it is every commit hash or it might be something our infrastructure does on deployment. I am not sure.

**Comment by pataquets** [comment]
When the 'create image tag for each branch' feature was introduced, I found that legacy ABs were not using it automatically. You have to add the blank, unconfigured line manually. However, it gets configured by default for new ABs.
It might be also that branches have slashes on names and I'm not sure of how this maps to image tags, not sure.
