### ISSUE TITLE
http/2 for public gateways

### ISSUE THREAD

**Issue by donothesitate** [ipfs/infrastructure#184]
**Use http/2 for public gateways.**

_Benefits:_
- avoiding stalls by hitting browser connection limit - 6 per domain (amplified by unresolvable resources on the page)
- avoiding RTT and TLS handshakes (amplified by random gateway selection - latency)
- lowering overhead of TCP (socket) context switching on loaded gateways
- faster loading time of mixed/small content, performance parity for large
- less CPU on both sides

nginx supported with module
caddy has support built in

**Comment by lgierth** [comment]
our nginx has accidentally supported http/2 for a while now :+1:
