### ISSUE TITLE
Setup PagerDuty

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/infrastructure#187]
Once we have AlertManager for setting levels on metrics, would be good to have something similar to PagerDuty for actually alerting us

**Comment by lgierth** [comment]
So, we have alerting set up via Grafana itself now, and it notifies a slack channel for every alert. It also has PagerDuty integration, so once we notice we want an on-call schedule, we can just go ahead.

**Comment by lgierth** [comment]
Note that for alerting itself, Slack's push notifications for the "alerting" highlight word should work just excellently.

**Comment by lgierth** [comment]
Closing this for now -- we have alerts in slack, we can revisit pagerduty later.
