### ISSUE TITLE
Setup proper TeamCity deploy

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/infrastructure#189]
Right now, TeamCity is running on an instance somewhere, without having any configuration scripts. We would like to try to setup our TeamCity instance in the following way:
- [ ] Ready-only settings - Only change settings and build configuration via changes in SCM
- [ ] Easier to deploy if something goes wrong - Master + Slaves setup in SCM

**Comment by lgierth** [comment]
Closing as we've moved to Jenkins
