### ISSUE TITLE
Gitter bridge

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#19]
@awrelll is setting up a gitter bridge. the goal is to get it to:

- [x] fully bridge gitter `ipfs/ipfs` with our freenode `#ipfs` channel.
- [x] make sure ALL messages said on IRC (freenode #ipfs) make it to gitter -- relayed by ipfs-gitter-bot
- [x] make sure ALL messages said on gitter make it to IRC (freenode #ipfs) -- relayed by ipfs-gitter-bot

I regained control of github.com/ipfsbot -- but im thinking that the gitter bridge should be its own account (cause we'll use ipfsbot for other things too), maybe `ipfs-gitter-bot`

---

As a note, until those three checkboxes above are robust, i dont feel ok telling people to use gitter. the last thing i want is for people to think we're ignoring them (if their messages arent getting through). an unreliable comm link can be worse than forcing people to use another comm link.

**Comment by awrelll** [comment]
It's done!

**Comment by jbenet** [comment]
verified the above. 

@awrelll what's involved here-- do you have to run a service somewhere? (recommend heroku if so-- simple servers mostly self manage)

**Comment by awrelll** [comment]
the bot is hosted on a server hosted by Vultr.

**Comment by jbenet** [comment]
ok-- if you're confident that'll stay up works for me.

**Comment by awrelll** [comment]
it will be up, have no worries :)

**Comment by jbenet** [comment]
thanks! :+1:

**Comment by jbenet** [comment]
@awrelll looks like https://gitter.im/ipfs/ipfs is broken

**Comment by harlantwood** [comment]
@awrell its down again.

**Comment by harlantwood** [comment]
@awrelll gitter bridge is down.

**Comment by harlantwood** [comment]
@jbenet said above:

> the last thing i want is for people to think we're ignoring them (if their messages arent getting through). an unreliable comm link can be worse than forcing people to use another comm link.

Hm, unfortunately I think we might be there now.  We should probably either increase reliability or kill the bridge, IMHO.
