### ISSUE TITLE
Decouple Bootstrap nodes IP from Droplet IP

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/infrastructure#190]
Right now, our bootstrap nodes addresses are coupled to the Droplet IP. It would be better if we could utilize the Floating IPs so we could spin up new Droplets if they somehow crash.
- [ ] Assign new Droplets Floating IPs
- [ ] Point go-ipfs default bootstrap list to Floating IPs rather than existing Droplet IPs

**Comment by lgierth** [comment]
We should do this very soon and try to get it into go-ipfs 0.4.5.

@Kubuxu @whyrusleeping how do you feel about an fs-repo-migration which replaces the current default addresses with new default addresses? The change itself is simple, I think we've just never changed the config file in a migraiton.

**Comment by VictorBjelkholm** [comment]
Shouldn't we keep running the current ones together with the new ones for a while, to make sure everything is working? I'd see the migration adding new addresses while not removing old ones, then after a while we can ship go-ipfs builds with only the new addresses.

**Comment by lgierth** [comment]
Instead of floating IPs we can just add `/dnsaddr` addresses to the bootstrap config, as per libp2p/go-libp2p#189

**Comment by hsanjuan** [comment]
seems I'm assigned to this... @lgierth I have the feeling multiaddresses now support dns resolution and that you did that and I see that the bootstrap config looks like:

```
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/ipfs/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/ipfs/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/ipfs/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd",
    "/ip6/2604:a880:1:20::203:d001/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM",
    "/ip6/2400:6180:0:d0::151:6001/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu",
    "/ip6/2604:a880:800:10::4a:5001/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64",
    "/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"
  ],
```

So this can be closed?

**Comment by lgierth** [comment]
Yes - thanks for checking :)
