### ISSUE TITLE
IPv6 bootstrappers and websites

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/infrastructure#191]
Right now, Bootstrap nodes only run IPv4. We would like to enable IPv6 to have better discoverability and connectivity.
- [x] Figure out what we have to do to enable IPv6 and setup following actions

**Comment by lgierth** [comment]
notes from #88
- [x] enable ipv6 for each droplet in an older datacenter
- [ ] programatically set ip addresses on hosts (i.e. /etc/network/interfaces et. al.)
- [ ] ~~give ipfs container an address from the /64 (https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)~~ not neccessary, ipfs container use the host network stack
- [ ] swarm listens on `/ip6/::/tcp/4001`
- [ ] ipv6 in default bootstrap list

and for the gateway:
- [ ] nginx listens on `/ip6/::/tcp/80` and `/ip6/::/tcp/443`
- [ ] AAAA records for ipfs.io, gateway.ipfs.io, and static pages

**Comment by lgierth** [comment]
ipfs.io, gateway.ipfs.io, as well as the default bootstrappers do now speak IPv6, and there's been a nice bump in the number of IPv6 peerings:

*Note: I restarted all these nodes to trick their peers into retrying, and possibly using /ip6 this time.*
![peers graph](https://ipfs.io/ipfs/QmQcUhRbkk9EDPdJHt4XHsGTEqH5yev7tdUUGJyBTSbF5g/screencap.2016-12-18T17:35:11Z.png)

Left to do:
- /ip6 addresses in the default bootstrap list of go-ipfs and js-ipfs
- DNS records for websites other than ipfs.io

**Comment by VictorBjelkholm** [comment]
Missing merged into go-ipfs to start using IPv6

**Comment by lgierth** [comment]
add /ip6 bootstrap config
- go-ipfs: https://github.com/ipfs/go-ipfs/pull/3523
- js-ipfs: ipfs/js-ipfs#706
