### ISSUE TITLE
Get SSL cert from a trustworthy CA

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#192]
Our current cert is from StartSSL :(

**Comment by Kubuxu** [comment]
Chrome 56 won't have WoSign in its CA chain: https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html

Planned release is January 31st, we should switch before the end of a year.

**Comment by llopv** [comment]
Let's Encrypt does not support wildcards but it is still very easy to configure with [certbot](https://certbot.eff.org/).
```
certbot certonly --standalone -d example.com -d www.example.com
```
And that's all.

**Comment by lgierth** [comment]
If we move on #212 relatively quickly, it can cover this issue.

**Comment by lgierth** [comment]
Closing in favor of #212
