### ISSUE TITLE
www.ipfs.io doesn't resolve

### ISSUE THREAD

**Issue by jesseclay** [ipfs/infrastructure#198]
some redirect weirdness here... more of an edge case than anything but should be fixed.

**Comment by lgierth** [comment]
Good suggestion, we don't have that subdomain set at all. We should probably also set it for all the other sites? I imagine we'd have a bit of nginx config which redirects to the non-www version.

**Comment by VictorBjelkholm** [comment]
Think we're using dnslink for deploying ipfs.io, so easiest would be to just add another record and update deploy commands in https://github.com/ipfs/website/blob/master/Makefile#L95 to include new record as well.

**Comment by jbenet** [comment]
it would be nice to -- where possible -- redirect to remove the `www.` prefix. it's just outdated.

**Comment by lgierth** [comment]
Uggh I don't know, then we'll also have to have www.ipfs.io/ipfs and /ipns -- *and support it forever*

**Comment by lgierth** [comment]
>  redirect to remove the www. prefix. it's just outdated.

and agree to that

**Comment by jbenet** [comment]
> _and support it forever_

ooof yeah-- that would suck. :)

**Comment by lgierth** [comment]
In the case of the redirect, we might want to consider having it only with a fixed set of domains, and not for everything that starts in www. People might legitimately have their www. domain pointed to the gateway. On the other hand, they might not, and in that case it would be useful to remove it, mh. This is essentially /ipns/example.com and /ipns/www.example.com.

Maybe this opens up space for a generic www-removal in go-ipfs-gateway itself, where we try to look up a dnslink for the www-version, and redirect to nowww if there's none. This means we'd still pick up the dnslink if the owner of the domain legitimately is using the www-version.

**Comment by lgierth** [comment]
Hehe funny how github turns just www into a hyperlink.

**Comment by jbenet** [comment]
@lgierth agree with your above proposal.

And, woah the link www works where I'm at today:

![image](https://cloud.githubusercontent.com/assets/138401/20198730/1bdfffe2-a75b-11e6-966c-956abe511bda.png)

**Comment by VictorBjelkholm** [comment]
Resolved to http://www.www.com/ for me in Firefox

Links...

**Comment by lgierth** [comment]
This is tracked in ipfs/go-ipfs-gateway#7
