### ISSUE TITLE
Enable github posting to #ipfs on all repos

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#2]
Currently only `ipfs` and `go-ipfs` are enabled.

**Comment by andyleap** [comment]
Have you thought about a more feature-full bot for the irc channel?

**Comment by jbenet** [comment]
I like many of the things hubot can do. Just don't want to take on the overhead of managing it myself. Have something in mind?



—

**Comment by andyleap** [comment]
just curious.  I've personally written my a few of my own bot irc bots for git pushes and stuff, where for private repos and stuff.  Not sure about hubot, I prefer golang myself.

**Comment by lgierth** [comment]
Is this still relevant? Not sure I'd want updates for dozens of repos flooded into #ipfs. Maybe #ipfs-commits or something like that?

**Comment by RichardLitt** [comment]
I think #ipfs-commits sounds good.

**Comment by harlantwood** [comment]
Maybe `ipfs-repos`?   Seems like we might want more repo activity that just commits....

**Comment by diasdavid** [comment]
:+1:
