### ISSUE TITLE
Reverse caching proxy 

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#200]
As ipfs grows hosing gateways might get more and more resource expensive. Reverse caching proxy, like [Varnish](https://varnish-cache.org/intro/index.html#intro) will greatly improve performance.

This is note for future, right now we want to stress go-ipfs.

**Comment by lgierth** [comment]
Can I close this since it's not actionable and not currently planned, and also a bit obvious? :) :tulip:

**Comment by lgierth** [comment]
Or mh nevermind, let's keep this open as a reminder that it might be a use case for others right now already, and come with some documentation or recommendations.
