### ISSUE TITLE
Setup https for ipld.io

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/infrastructure#203]
Currently, visiting ipld.io works fine, https://ipld.io does not work fine we're using the ipfs.io certificate for it, leading to errors in the browser.

We need to setup https properly for ipld.io

* [ ] Acquire certificate for ipld.io
* [ ] Setup nginx to serve different certificates for different hosts (this should setup in way it'll be easy to add multiformats.io and libp2p.io once we have those ready as well)

**Comment by Kubuxu** [comment]
When we are getting cert for ipld.io we might want to resolve https://github.com/ipfs/infrastructure/issues/192 at the same time.

**Comment by VictorBjelkholm** [comment]
Yeah, and also get certs for libp2p.io and mutliformats.io and the orbit website

**Comment by lgierth** [comment]
I'd propose we look into automatic let's encrypt certs for non-ipfs.io domains. That'd benefit anyone using the gateway.

**Comment by VictorBjelkholm** [comment]
Note: This is blocking the deployment and finalization of shipping the ipld.io website

**Comment by Kubuxu** [comment]
It is quite easy with certbot and can be done without it modifying nginx configs (one manual config edit), the `.well-known/acme-challenge/` has to be redirected to some webroot and the the certbot has to be run, ref: https://loune.net/2016/01/https-with-lets-encrypt-ssl-and-nginx/

**Comment by lgierth** [comment]
> I'd propose we look into automatic let's encrypt certs for non-ipfs.io domains. That'd benefit anyone using the gateway.

I've looked into this a bit and put my notes in #212. @VictorBjelkholm if it's urgent we can still do the ipld.io cert manually before this.

**Comment by lgierth** [comment]
Closing in favor of #212
