### ISSUE TITLE
Travis build cancelation

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#209]
There is beta feature in Travis that cancels existing job if new commit in branch is created or the branch is force-pushed to. It would greatly reduce load on Travis thus probably increasing the throughput.

Would everyone be ok with enabling that feature? @whyrusleeping @diasdavid @dignifiedquire @VictorBjelkholm @lgierth 

I would have to email the support and ask them to do it as it is still in "closed" beta, they might want authorization from owner of the org but we will see.

**Comment by lgierth** [comment]
I like it

**Comment by diasdavid** [comment]
Yes please :D

**Comment by dignifiedquire** [comment]
yes, yes and yes

**Comment by VictorBjelkholm** [comment]
Makes a lot of sense, go for it!

**Comment by Kubuxu** [comment]
Sent the email.

**Comment by Kubuxu** [comment]
The feature was enabled for our repos in libp2p and ipfs.

If you have some repos where you frequently go through push,dev,push,dev,push,dev process enable this feature in settings tab of this repo.

I have already enabled it for go-ipfs.

**Comment by dignifiedquire** [comment]
Thank you @Kubuxu
