### ISSUE TITLE
Video Meeting tools

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#21]
We ran into the 10 person google hangouts limit today. i dont think google live hangouts helps much here.

Others have suggested:
- talky.io
- zoom.us
- palava.tv

main requirements are:
- works on all platforms (so ideally webrtc)
- good video / audio quality
- trivial for new users to use (e.g. no need for accounts (link / invite only) )

**Comment by whyrusleeping** [comment]
everyone should also make sure that they get the best internet connection they can for calls like this. use ethernet if at all possible.

**Comment by salsa-dev** [comment]
have you found one that meets your requirements ?

I'm using BigBlueButton for such meetings.

**Comment by RichardLitt** [comment]
We haven't; we switched from using Google Hangouts to using the IRC group and splitting up the meetings into smaller endeavors. 

We will need to find a solution for this at some point.

**Comment by em-ly** [comment]
I think everyone is happy with zoom.us so closing this issue!

**Comment by hermanjunge** [comment]
`zoom.us` has worked like a charm in my company (`ConsenSys`)

**Comment by whyrusleeping** [comment]
@hermanjunge we took the hint from you guys when we visited :)

**Comment by jbenet** [comment]
Zoom is fantastic, 5/7 would video call again.

**Comment by hermanjunge** [comment]
<img width="392" alt="screen shot 2016-07-07 at 2 18 20 am" src="https://cloud.githubusercontent.com/assets/729830/16644211/1fa3bd2e-43e9-11e6-89a2-99862f166bea.png">
