### ISSUE TITLE
Anycast BGP for ipfs.io

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#216]
Filing this as a wildcard for the collab with @kyledrake

We're getting a /24 or /25 IPv4, /48 IPv6, ARIN membership, and AS number, then announce the gateway's IP addresses from multiple locations.

**Comment by lgierth** [comment]
Great news! We can start right away. For now we'll be borrowing a small portion of Neocities' IP blocks: http://bgp.he.net/AS395409

> ASNumber: 395409
> ASName: NEOCITIES
> ASHandle: AS395409
> Prefixes v4: 198.51.233.0/24
> Prefixes v6: 2620:2:6000::/48

It's going to be 198.51.233.224/28 and 2620:2:6000:26::/64.

```
Network:   198.51.233.224/28
HostMin:   198.51.233.225
HostMax:   198.51.233.238
Broadcast: 198.51.233.239
Hosts/Net: 14
```

The first thing to do is likely the gateway, which can be:
- 198.51.233.233
- 198.51.233.234
- 2620:2:6000:26::26
- 2620:2:6000:26::27

**Comment by lgierth** [comment]
I've pointed the new dweb.link domain at these IPs. You can already `mtr -4 dweb.link` and `mtr -6 dweb.link` to see anycast BGP in action. There's just no gateway running behind it yet.

dweb.link is eventually going to replace ipfs.io as the public gateway.

**Comment by kyledrake** [comment]
The BGP exports look good!

It looks like 198.51.233.233 and 2620:2:6000:26::26 are pinging, but the secondaries are not. Might want to check and see if there's an interface configured for them.
