### ISSUE TITLE
Calendar(s)?

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#22]
We should have a calendar (or set of calendars) for important dates + community events (talks, etc).

We can setup google calendars @ipfs.io and have it listed to be publicly viewable somewhere. Does that sound good, or are there other services people want to try?

**Comment by chriscool** [comment]
That sounds good to me.

**Comment by harlantwood** [comment]
Hm.  Wherever I've seen Google calendars embedded on sites they always look a bit crummy and uninviting... Having said that it's the most practical option I am aware of.

If we wanted to get a bit radical we could consider using [Timeline JS](http://timeline.knightlab.com/), which you control from a Google spreadsheet.  

It's easy to imagine forking timeline JS to make a version backed by ipfs!

**Comment by lgierth** [comment]
We have community and team calendars now
