### ISSUE TITLE
Metrics host "banana" needs a better name

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#221]
In the spirit of banana-driven development, I gave it an annoyingly silly name so that I'd *have to* eventually come up with a better name.

Proposed new name: mula

> Mūla ("root") (Devanagari मूल/मूळ) (Tamil: மூலம்) is the 19th nakshatra or "lunar mansion" in Vedic astrology and corresponds to the stars ε, ζ, η, θ, ι, κ, υ, λ, μ and ν Scorpii in the tail/sting of Scorpius. The symbol of Mula is a bunch of roots tied together (reticulated roots) or an 'elephant goad' (ankusha) and the Deity associated with it is Niriti, the god of dissolution and destruction. The Lord of Mula is Ketu (south lunar node).
>
> The moon in Mula indicates a person who has a passionate desire to get to the truth and is good at investigation and research. They are direct, ardent and truthful and are shrewd and ambitious, but they can feel trapped and bound by circumstances and so feel resentment and a sense of betrayal. They can also suffer extreme reversals of fortune that may involve pain and cruelty. This nakshatra indicates some "adverse events" in respect of parents, especially father. E.g. Sant Jnaneshwar.
>
> The centre of our galaxy, the Milky Way, lies in this nakshatra, hence the name Mula.[citation needed]
>
> Under the traditional Hindu principle of naming individuals according to their birthstar (see Jyotisha), the following Sanskrit syllables correspond with this Nakshatra, and would belong at the beginning of a first name: Ye, Yo, Bha or Bhi.
>
> -- https://en.wikipedia.org/wiki/Mula_(nakshatra)

**Comment by lgierth** [comment]
Oh wait that's from astrology. Nevermind, I'll find something else.

**Comment by Kubuxu** [comment]
I suggest Atira which is asteroid in earth's orbit: https://en.wikipedia.org/wiki/Apohele_asteroid

**Comment by lgierth** [comment]
SGTM :+1: 

> Given (163693) was discovered by the LINEAR program which operates out of the southwestern United States, preference was also given to a name of local origin. The minor planet was named after Atira, a goddess of the Native American Pawnee people. She is the wife of the creator god, Tirawa, and goddess of Earth and the evening star.

**Comment by lgierth** [comment]
The websockets bootstrappers `strawberry` and `blueberry` need a name too.

**Comment by Kubuxu** [comment]
They are ws bootstrap hosts aren't they? My suggestion `a-cen-a` and `a-cen-b` from which would be short forms from Alpha Centauri A and B. After all they are on an edge of unknown world (of websockets and browsers).

**Comment by lgierth** [comment]
By now I feel like the hostname `banana` is just fine -- it'll be decommissioned in the midterm
