### ISSUE TITLE
Using GitCop

### ISSUE THREAD

**Issue by chriscool** [ipfs/infrastructure#23]
We want to use [GitCop](https://gitcop.com) to make sure the commits have the following trailers:

```
License: MIT
Signed-off-by: user name <email@address>
```

We might also limit the subject of each commit to 80 characters.

What do you think?

**Comment by harlantwood** [comment]
Hm,  I think this page says max commit subject of 50 characters:

https://github.com/ipfs/community/blob/master/contribution-guidelines.md

**Comment by chriscool** [comment]
Yeah we can decrease it to 50, but I think it will make too much noise for not much gain as 80 should still be readable for most people.

It might only be better for people looking at commits from smartphones, as today terminals are usually much wider than 80 characters and web browsers on recent desktop or laptops also have no problem with 80 characters.

**Comment by jbenet** [comment]
ok 80 sounds good

**Comment by jbenet** [comment]
Maybe the gitcop message should mention the commit hook directly too

**Comment by jbenet** [comment]
@spikebike just had a hard time figuring out how to make this happen. maybe also have a couple of commands that guide people to amending their commits? (many people dont know how to use git rebase)

**Comment by chriscool** [comment]
@jbenet ok I will improve the GitCop message and https://github.com/ipfs/community/blob/master/docs/commit-message.md soon.

**Comment by lgierth** [comment]
@chriscool can this be closed?

**Comment by chriscool** [comment]
Yes, let's close this.

**Comment by chriscool** [comment]
Sorry but I think we should probably reopen this, as it is referenced in the GitCop message where we ask people to provide their feedback in this issue.

**Comment by chriscool** [comment]
By the way the GitCop footer message is now:

```
We ask for a few features in the commit message for Open Source licensing hygiene and commit message clarity.
`git commit --amend` can often help you quickly improve the commit message.
[Guidelines](https://github.com/ipfs/community/blob/master/contribution-guidelines.md#commit-messages) and [a script](https://github.com/ipfs/community/blob/master/dev/tools/hooks/setup_commit_msg_hook.sh) are available to help in the long run.
Your feedback on GitCop is welcome on [this issue](https://github.com/ipfs/infrastructure/issues/23).
```

Tell me if you see something that can be improved in it.
But note that GitCop for now doesn't let us provide a customized error message for each different error that can trigger it.

The different errors that can trigger it are the following:

- the subject is more than 80 characters long
- the commit message doesn't contain:

```
License: MIT
Signed-off-by: user name <email@address>
```

**Comment by RichardLitt** [comment]
GitCop should delete it's comments when someone PRs a fix to the commit and there is no longer an issue.

**Comment by chriscool** [comment]
Yeah, that might be a good idea. I will suggest it.

**Comment by chriscool** [comment]
The changes we requested have been taken care of by Gary, the GitCop guy, and I have changed the GitCop configuration for the go-ipfs repo.

Now the GitCop messages are attached to individual commits, so when the commit are fixed, the GitCop comment will be masked by default by GitHub.

Also as https://github.com/ipfs/community/pull/126 is merged, each specific GitCop error messages have been customized to have a link to a specific section in https://github.com/ipfs/community/blob/master/contribution-guidelines.md
