### ISSUE TITLE
Migrate from Ubuntu 14.04 to something more recent

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#231]
Maybe just to 16.04 -- one way or the other a Systemd-based OS would be good, and this will involve migrating a few services off Upstart (node_exporter, cjdns).

@Kubuxu you said you'd prefer Debian, got more info why that'd be useful?

**Comment by Kubuxu** [comment]
It is lighter (package wise), it is created with as a server base distro and it reduces our risk chain by removing whole company from it (Canonical).

**Comment by lgierth** [comment]
> will involve migrating a few services off Upstart (node_exporter, cjdns).

These two now support both upstart and systemd, so we can go ahead with whatever we feel like. A small handful of hosts is already running ubuntu 16.04, and I'd like to try Debian on some too.

@Kubuxu which version would you say we should try?

**Comment by Kubuxu** [comment]
Debian 8 aka Jessie
