### ISSUE TITLE
dists page with 0.4.5-rc1

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#236]
https://ipfs.io/ipfs/QmWpeFq2yT6ES4KYHsdSPAmNEUjDxnJEK3nP2oEXZRHbVq/

**Comment by lgierth** [comment]
Semi-blocked by ipfs/distributions#135, not sure what to do

**Comment by lgierth** [comment]
New dag with linux-musl build of fs-repo-migrations reinstated: QmRL68pNeqtKGBPJBmX21UKVpTSKcKKsvWDbKBzRyeQ9Jv

**Comment by lgierth** [comment]
done
