### ISSUE TITLE
Auto-run labels-and-milestones and roadmap-generator on commit

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/infrastructure#240]
This would satisfy https://github.com/ipfs/pm/issues/257, https://github.com/ipfs/pm/issues/237 and  https://github.com/ipfs/pm/issues/362

See those issues for explanation of why we need this.

### Given 
* we have chosen a location where the `labels-and-milestones` and `roadmap-generator` config files live (probably ipfs/pm/tools)
* we have added copies of the `labels-and-milestones` script and the `roadmap-generator` script to that repository

### Then
* Configure a task runner that has write access to all of the repos referenced in any of those config files

### And Then
* When someone commits a change to one of those config files, the task runner automatically re-runs the `labels-and-milestones` sync command (probably triggered by CI server)
* And the task runner reports the output from the command (in case something went wrong) - preferably in the CI server
* And the task runner re-generates the "roadmap.md" with `roadmap-generator` script
* And the task runner pushes the resulting project-specific "roadmap.md" to the repo where we're storing those files (probably ipfs/pm)

## Example code:
* For configuring & running `labels-and-milestones`: https://github.com/ipfs/go-ipfs/pull/3389
* For configuring & running `roadmap-generator`: https://github.com/ipfs/go-ipfs/pull/3390

**Comment by flyingzumwalt** [comment]
@VictorBjelkholm is this something we can set up with jenkins?

**Comment by Kubuxu** [comment]
It might be easier with simple git hook and and running the script in dokku but I am not sure.

**Comment by lgierth** [comment]
I think we can use the github-integrated bot that @dignifiedquire wrote the other day as a base for this. And maybe run it off a cloud.ipfs.team "clone" on a trusted machine.
