### ISSUE TITLE
0.4.5 release candidate 3 dists page

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#244]
https://ipfs.io/ipfs/QmQrNZ31w4q4c3JD4pzfeDJCV5AiLDi7GcWzjNhNaZepwy/

**Comment by whyrusleeping** [comment]
disregard, more changes coming...

**Comment by whyrusleeping** [comment]
Alright,
0.4.5 rc4

https://ipfs.io/ipfs/QmWtatYEBceptae1m8mtdXKVVfJ8gYdazoAmaDS8Sz2PLD

**Comment by lgierth** [comment]
updated: https://dist.ipfs.io
