### ISSUE TITLE
A website loaded through dnslink with a `/blog` will get the ipfs/blog loaded instead of that page's blog

### ISSUE THREAD

**Issue by diasdavid** [ipfs/infrastructure#247]
Just caught a funny bug by chance while merging my webpage and blog into a new hugo theme. As usual, I've updated the DNS record to point to the new hash, which loads perfectly, but when I go into `QmHash/blog`, I get the ipfs blog instead of mine.

Webpage - https://ipfs.io/ipfs/QmP1zwSvLUa6vVZjmCEH4fSEszuV8bKw71SY4RJyW3duAJ/
Domain - http://daviddias.me
Error- http://daviddias.me/blog

I believe this is because the nginx configs have a rule for a /blog/ to redirect to another hash, causing every page that uses DNSLink to not be able to use that link.

**Comment by Kubuxu** [comment]
Already reported: https://github.com/ipfs/infrastructure/issues/224

**Comment by diasdavid** [comment]
ah, thanks @Kubuxu , closing this one then :)
