### ISSUE TITLE
dists page with new fs-repo-migrations

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#249]
https://ipfs.io/ipfs/QmZMzC8ihgybDLzstWm9iYTEbrhVEeBtevWE6vLjdci3Ay/

**Comment by lgierth** [comment]
with musl: https://ipfs.io/ipfs/QmNoJXHBug2GLoRdqeznH7Y79CRGc13H4k3QLYLeARcEsk/

Let's just move away from musl, this is not worth the effort and complexity.

**Comment by lgierth** [comment]
ok -- https://dist.ipfs.io/

ready for update in migrations.go
