### ISSUE TITLE
Do a clearnace chore with OVH

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#250]
During the CI sprint we got bitten by this. It might be needed for the Testbed sprint.

@lgierth will you take that? If you don't want to, I can try doing it.

**Comment by lgierth** [comment]
@Kubuxu if you could take it that'd be awesome, OVH has been my personal nightmare :)

**Comment by lgierth** [comment]
> - One piece of government issued ID confirming your Identity and date of birth.
> - An invoice addressed to you dated from within the last two months.
> - The front of the credit card used to pay this order, hiding the first 12 numbers of your card number.
> - The back of the credit card used, with the CCV number hidden.

**Comment by lgierth** [comment]
Yay it's done \o/
