### ISSUE TITLE
New distributions page

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#253]
Ipfs 0.4.6
ipfs-update1.5.1
ipfs-pack 0.1.0
ipget 0.3.0

https://ipfs.io/ipfs/QmPF3Z8hHoqyNKcZovCZSLwyWAvWRtuWto1Lzy47i18GiG/

**Comment by lgierth** [comment]
yay :D now for the merge fest

**Comment by lgierth** [comment]
done

**Comment by jbenet** [comment]
Guys, this is broken: https://github.com/ipfs/ipfs-update/issues/55 ...
