### ISSUE TITLE
Guess what! New dists page :)

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#259]
https://ipfs.io/ipfs/QmQCSYBkVKY2Am8WU8iJ2i2qYB59TyiPHs9ZxASuxsEkbH/

ipfs 0.4.7 rc1

**Comment by whyrusleeping** [comment]
Oh look, 0.4.7 is out now:
https://ipfs.io/ipfs/QmQzv4n3d55aQ5P4d9yTpNuph2ijG7T2qNGmkebQLnEAo7/

**Comment by lgierth** [comment]
dooone https://dist.ipfs.io
