### ISSUE TITLE
new dists build

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/infrastructure#271]
https://ipfs.io/ipfs/QmWbqocNBQEDUG7PzT9oACvymhwe3h2tDoMhfJTDAZeddp/

Ipfs 0.4.8, woot woot

**Comment by whyrusleeping** [comment]
Heres with the new ipfs-cluster binaries:
https://ipfs.io/ipfs/QmQV4baHyV7FFaF4j7BQZYEXSSABFYY4YkWFMAscf6fm62

cc @hsanjuan

**Comment by hsanjuan** [comment]
Thanks @whyrusleeping !

**Comment by whyrusleeping** [comment]
i published

**Comment by lgierth** [comment]
Thanks!
