### ISSUE TITLE
IPFS on Synology DSM

### ISSUE THREAD

**Issue by JayBrown** [ipfs/infrastructure#288]
Anyone managed to install IPFS on a Synology running the default DSM?

Couldn't find anything anywhere.

**Comment by lgierth** [comment]
Closing this as there's no responses and it's a tiny bit off-topic in this repo.

You might have more luck in discuss.ipfs.io :)

**Comment by asymmetric** [comment]
For those that are interested, this is the [forum discussion](https://discuss.ipfs.io/t/go-ipfs-on-synology-dsm/1097)
