### ISSUE TITLE
Stop keeping container logs

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#29]
Docker currently keeps the complete log of the container, which we throw away anyhow since IPFS keeps its own logs. Docker 1.6 introduced the `--log-driver` option which we can set to `none`.

Ansible implements this in 2.0 which isn't released yet. Relevant commit: https://github.com/ansible/ansible-modules-core/commit/718f32a042ee40d6c5426349116722c0fb77d998

**Comment by jbenet** [comment]
:+1:

**Comment by lgierth** [comment]
It turns out that `--log-driver` can also be set for the docker daemon. I just did that manually on all gateway hosts and restarted the daemon afterwards.

I need to codify it, will do that later in the night.

**Comment by lgierth** [comment]
Steps to reproduce:

```sh
$ ansible gateway -m shell -a 'echo DOCKER_OPTS="--log-driver=none" >> /etc/default/docker'
$ ansible gateway -f 1 -a 'restart docker'
```

**Comment by lgierth** [comment]
Also did the same on all other nodes (util,metrics,storage)

**Comment by jbenet** [comment]
Awesome, thanks.
