### ISSUE TITLE
Implementation independent tests

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#3]
I want to have a full implementation-independent test suite, including things like the current network test, and the sharness tests. This will allow developers of other implementations to benchmark against another test suite.

This requires:
- making a new repo for this -- perhaps `impl-tests`
- moving sharness, network test, whatever else there.
- the full `make test` in go-ipfs should still run these tests, so perhaps it can clone the repo locally.

implementations wont have all the same sets of features, e.g. some implementations may be missing gateways, or missing the CLI altogether, or even the API (but still have the protocol implemented). It would be ideal if the test suite allowed implementors to pick the sets of test cases to run. Perhaps something like:
- `protocol` for full protocol tests
- `API` for testing conformance to the the api spec
- `cli` for testing cli tools.

Maybe we should fully decouple the cli in go-ipfs, so that it can be used against other language implementations of the API just as well.

This is a big project. Starting the conversation, as people are itching to get started with implementations in other languages.

**Comment by lgierth** [comment]
Deferring this to https://github.com/ipfs/interface-ipfs-core
