### ISSUE TITLE
HTTPS redirects

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#305]
We should enable HTTP-to-HTTPS redirects for all dnslink pages on the gateways.

For ipfs.io and gateway.ipfs.io, only the root should redirect, so that deeplinks to e.g. /ipfs/QmFoo still work without HTTPS if they have to. There's tools and devices with broken or missing HTTPS support.

**Comment by awnumar** [comment]
In addition to `301` redirects,

* At least double (preferably quadruple) the max-age on your HSTS policy.
* Stop returning the HSTS header on the HTTP (now redirected) response.

**Comment by lgierth** [comment]
This has been done in the meantime, thanks for weighing in @awnumar!
