### ISSUE TITLE
Add http cache infinity header to all the /ipfs/Qmhash paths

### ISSUE THREAD

**Issue by diasdavid** [ipfs/infrastructure#309]
This way, browsers don't have to hit the gateways after they first loaded an IPFS hash :)

Idea by the great @olizilla \o/

**Comment by lgierth** [comment]
We've already been doing that for ages: https://github.com/ipfs/go-ipfs/blob/eef022cd5ecfc818205b6d015772f411bc18a3e8/core/corehttp/gateway_handler.go#L253-L258
