### ISSUE TITLE
If ipfs.io was never vistited under HTTPS browsers will use HTTP

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/infrastructure#316]
Fresh WIndows 10 VM, Firefox 54.0.1.

Going to `ipfs.io` brings up the HTTP version of the page. After the `https://ipfs.io` was visited it is being used for now on.

This is the problem with us not redirecting (which is what we wanted to do), but it might want to rethink that.

**Comment by lgierth** [comment]
Yeah I made #305 the last time you complained :D

**Comment by Kubuxu** [comment]
This is just additional factor I discovered. That is why I decided to report it. :P

**Comment by lgierth** [comment]
I think it's simply because we send the HSTS header on http as well (which we shouldn't)
