### ISSUE TITLE
Brave/BAT verify ipfs.io and the other websites

### ISSUE THREAD

**Issue by diasdavid** [ipfs/infrastructure#347]
Our brave 🦁 friends invited us to verify our websites so that we could collect Brave Tokens. More than collecting the tokens, it is a good way for us to give feedback to their platform by experimenting with it first hand.

Apparently the process is simple, we just need to go to https://publishers.basicattentiontoken.org/

@lgierth thoughts?

**Comment by lgierth** [comment]
Can we limit this to certain subpages? It's okay to have ipfs.io and other project websites covered by this, but it's *not* okay for us to get paid for gateway content.

**Comment by lgierth** [comment]
Anybody feel free to pick this up - I can help out with the DNS records for verification.

**Comment by lukemulks** [comment]
Hi, @lgierth I work at Brave and am on the BAT team. Adding some info from our end re: intent and utility.  

To clarify, verification should only apply to the ipfs.io website, and is not intended to be applied for gateway content.

If gateway content is hosted with the ipfs.io domain, LMK. If this is the case, I can inquire internally to determine if we can potentially blacklist any subdomains or other URLs from eligibility if they use ipfs.io in addition to the project website. 

If it's too much hassle, or a blocker for your use case, not the end of the world. Totally understand respect (and share) the concern wrt gateway content. 

If I can be of any assistance with the process or questions, feel free to tag me here. Happy to help from our end.

**Comment by lgierth** [comment]
> If gateway content is hosted with the ipfs.io domain, LMK

Yeah that's the case :) We have the project website https://ipfs.io, and then content at e.g. https://ipfs.io/ipfs/QmPCawMTd7csXKf7QVr2B1QRDZxdPeWxtE4EpkDRYtJWty - the paths involved here are /ipfs, /ipns, /ws, and /api. We will be separating this soon though, aiming for end-of-year. These four paths will then be redirected to https://dweb.link

What do you think?

**Comment by lgierth** [comment]
Closing this for now - I'm sure we'll get back to it :100:
