### ISSUE TITLE
Update dists.ipfs.io for ipfs 0.4.13

### ISSUE THREAD

**Issue by Stebalien** [ipfs/infrastructure#349]
New hash: [/ipfs/QmTZ4poXXMgCcwTP12LztyynbKXTnoKBZDdDRbUGk7TLiN](https://ipfs.io/ipfs/QmTZ4poXXMgCcwTP12LztyynbKXTnoKBZDdDRbUGk7TLiN)
Dists PR: https://github.com/ipfs/distributions/pull/164

**Comment by whyrusleeping** [comment]
updated
