### ISSUE TITLE
Set up alerts for critical conditions

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#36]

**Comment by jbenet** [comment]
(not sure if this is the right issue, but:) Would be nice to have a pinger/pager service. something like pingdom or goffee.io (goffee uses TOR to check URLs from various places. it's very simple, which is both good and bad). no preference here. (most good services will be paid services)

**Comment by davidak** [comment]
I'm using the free option of https://uptimerobot.com/ (50 HTTP Checks, every 5 min.)

A check every minute would be better but is not free.

Also Grafana has now a [worldPing Plugin](https://grafana.net/plugins/raintank-worldping-app).

Grafana is also working on an [alerting system](https://github.com/grafana/grafana/issues/2209), could be useful for your node monitoring.

**Comment by lgierth** [comment]
closing in favor of #187
