### ISSUE TITLE
Create mailing list for core working group

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/infrastructure#383]
@lgierth or @diasdavid could you make a core-wg@ipfs.io mailing list and add these people to it?

- @jbenet 
- @diasdavid 
- @whyrusleeping 
- @flyingzumwalt
- @lgierth 

Notes: 
- The actual definition of the core WG and its membership is not fully settled. See https://github.com/ipfs/rfcs/pull/2 -- but we need this mailing list in order to coordinate the work that will _finish_ at RFC so we can formally create WGs. 
- The contents of this list will probably be made publicly viewable, but in the meantime we need a way to flag conversations for this group.

**Comment by eefahy** [comment]
moved to https://github.com/protocol/it/issues/6
