### ISSUE TITLE
Move gateway to ipfs.io

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#4]
We want to have the gateways at `ipfs.io` instead of `gateway.ipfs.io`

This requires
- [ ] IPNS proved robust enough for ipfs.io website.
- [ ] faster gc on the gateways
- [x] period reboot on the gateways (clear any bad states, etc)

**Comment by lgierth** [comment]
> IPNS proved robust enough for ipfs.io website

This isn't neccessarily a dependency. We can easily point `ipfs.io/ipfs` and `ipfs.io/ipns` to the port 8080.

**Comment by jbenet** [comment]
@lgierth yeah, we could either:

1. use nginx rewriting to redirect `/ --> /ipfs/<root-hash-of-ipfs-website>` so it gets hosted by ipfs.
2. host https://github.com/ipfs/website directly from nginx as a backup

**Comment by jbenet** [comment]
it may be nice to make (1.) possible from within go-ipfs itself. So we could:

```
ipfs config Gateway.HttpRoot <root-hash-of-ipfs-website>
```
and have
```
curl http://<host>/foo/bar
```
use 
```
/ipfs/<root-hash-of-ipfs-website>/foo/bar
```

**Comment by lgierth** [comment]
Remaining steps:

- [ ] get additional SSL certs for ipfs.io and dogfeed.ipfs.io
- [ ] use SSL SNI to pick ipfs.io/gateway/dogfeed cert
- [ ] Make /ipfs and /ipns work with self-hosted ipfs.io -- https://github.com/ipfs/infrastructure/pull/72
- for arbitrary pages:
  - [ ] https://github.com/ipfs/go-ipfs/pull/1615 -- https://github.com/ipfs/go-ipfs/pull/1615
  - [ ] use SSL SNI to refuse handshakes for anything that we don't have a cert for

**Comment by jbenet** [comment]
![](http://replygif.net/i/758.gif)
