### ISSUE TITLE
Add Mike Goelzer to the IPFS org

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/infrastructure#403]
Please add @mgoelzer to the IPFS Github org and add him to (at least) the [pm team](https://github.com/orgs/ipfs/teams/pm/members?utf8=%E2%9C%93&query=)

**Comment by flyingzumwalt** [comment]
He doesn't show up on the pm team https://github.com/orgs/ipfs/teams/pm/members?utf8=%E2%9C%93&query=mgoelzer is there a step missing?

**Comment by VictorBjelkholm** [comment]
@flyingzumwalt he hasn't accepted the invitation. Should check his mail or go directly to https://github.com/ipfs and there will be a banner in the top of the page

**Comment by mgoelzer** [comment]
I've attached the invitation.

**Comment by flyingzumwalt** [comment]
great! you're on the pm team now. That will give you write access to a bunch of stuff, and lets people assign things to you.
