### ISSUE TITLE
Allow non-ipfs.io accounts to log into ipfs.io google groups

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/infrastructure#405]
This is really annoying. Somehow, somewhere in the settings of the ipfs.io google apps account, it's set to only allow ipfs.io accounts to view the google groups. That means we can subscribe other email addresses but those people can't change their subscription preferences or view the conversations in the google groups web UI. 

How can we fix this? As working groups grow some of them are inevitably going to want mailing lists. I want to be able to provision those lists easily.

**Comment by lgierth** [comment]
Non-jbenet ipfs.io admins are blocked by @jbenet backing up a bunch of stuff in that ipfs.io gapps, and then recreating that gapps account.

**Comment by eefahy** [comment]
Moved to `it` repo https://github.com/protocol/it/issues/5
