### ISSUE TITLE
Update dists for fs-repo-migrations release

### ISSUE THREAD

**Issue by Stebalien** [ipfs/infrastructure#408]
Dists PR: https://github.com/ipfs/distributions/pull/190
Published: ~/ipfs/QmZLYJBVBK8nqc5JTHp6CZU1v9Ja3MvGrkCe61PfCecc6E~

---

Update for fs-repo-migrations and fix the current windows gx release:

/ipfs/QmYpvspyyUWQTE226NFWteXYJF3x3br25xmB6XzEoqfzyv

**Comment by Stebalien** [comment]
@whyrusleeping not done.

**Comment by whyrusleeping** [comment]
updated again

**Comment by Stebalien** [comment]
Sorry, that was a bit confusing.

The "not done" was orthogonal to the updated dist path (that was just a "while you're fixing this, we might as well use the latest dist path").

By "not done", I meant "the DNS record has not been updated". However, given your comment, I assume it simply got reverted. That's probably because DNS is now configured through terraform (and someone probably re-applied the configuration):

https://github.com/protocol/infra/blob/master/dns/dist.ipfs.io.tf

I'd fix this, but I don't have a DNSimple token. See: https://github.com/protocol/infra/blob/master/dns/README.md

**Comment by whyrusleeping** [comment]
ah, interesting. okay. This is a new process to me, who does this?

**Comment by lgierth** [comment]
fs-repo-migrations 1.4.0 has been there for a while
