### ISSUE TITLE
https://ipfs.io domain is taking a long time to find files from a go-ipfs node

### ISSUE THREAD

**Issue by rodkeys** [ipfs/infrastructure#409]
A few months ago when I was using my go-ipfs node I was able to add files and have it discovered by https://ipfs.io/ipfs/*hash* within seconds. In the last few weeks I have found that this now often takes multiple minutes. I have tested it on multiple VPS's in different locations and have experienced the same issues. Is this a known issue by other members of the team?

**Comment by kyledrake** [comment]
What is the specific hash you're seeing this issue with?

Could you provide the results of traceroute -A ipfs.io for a VPS having the issue?

**Comment by lgierth** [comment]
This seems to be much better now
