### ISSUE TITLE
Is there a public Cjdns gateway to reach the bootstrap nodes?

### ISSUE THREAD

**Issue by zciendor** [ipfs/infrastructure#414]
It would be great if one could bootstrap IPFS via Cjdns only. However, I can't find a public Cjdns gateway that is connected to the bootstrap nodes (pluto, neptune, neptune, uranus, saturn, jupiter, venus, earth, mercury, banana, scrappy, chappy, pollux, nihal, biham, auva).

Those nodes are publicly reachable via IPv4 and IPv6 anyway... is there any reason, why they shouldn't allow public Cjdns connections? Or what about at least operating a public Cjdns gateway in front of them in each geography?

**Comment by lgierth** [comment]
We're not currently planning to revive cjdns support for the gateway or bootstrappers. We'd be delighted if you run your own nodes on cjdns though!
