### ISSUE TITLE
Deploy latest go-ipfs master to the Gateways and bootstrappers

### ISSUE THREAD

**Issue by diasdavid** [ipfs/infrastructure#415]
0.4.16 introduced a regression that makes transfers of `go => JS` almost certainly fail (more context here https://github.com/ipfs/interop/pull/28). @Stebalien already fixed it but it hasn't been released.

Can we have the gateways with latest go-ipfs master so that things go as smooth as possible for the demos coming?

An alternative solution is to get another go-ipfs release next week and updating the gateways with that. Just putting the two options there, the second is better but we need at least one of them.

**Comment by diasdavid** [comment]
//cc @lgierth @Stebalien @whyrusleeping

**Comment by lgierth** [comment]
> Can we have the gateways with latest go-ipfs master so that things go as smooth as possible for the demos coming?

Okay on it
