### ISSUE TITLE
New ws-star for peerpad in SF

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/infrastructure#416]
We should add a new ws-star instance located in or close to SF

This deployment should handle up to 100 simultaneously connected peers (connected + sending data).

I'll start by creating the same instance type as we use for the Paris one, @pgte will do some benchmarking and then we'll adjust the type if needed.

**Comment by diasdavid** [comment]
Good thinking @VictorBjelkholm!! //cc @pgte

**Comment by VictorBjelkholm** [comment]
Deployed over at `/dns4/ws-star2.sjc.dwebops.pub/tcp/443/wss/p2p-websocket-star` and should work (tested with local version of peerpad)
