### ISSUE TITLE
Update dist.ipfs.io

### ISSUE THREAD

**Issue by Stebalien** [ipfs/infrastructure#420]
PR: https://github.com/ipfs/distributions/pull/194
New Path: /ipfs/QmNuyz8s1MZHPBp3nu4hnAXJyXbyZXdVkJfKu38JiSv7KC

**Comment by lgierth** [comment]
Ok

**Comment by lgierth** [comment]
For the next ones, you can now make PRs against [protocol/infra/dns/dist.ipfs.io.tf](https://github.com/protocol/infra/blob/master/dns/dist.ipfs.io.tf) -- the deploys of that will also be automated soon.
