### ISSUE TITLE
CI pipeline for js-ipfs and js-ipfs-api

### ISSUE THREAD

**Issue by alanshaw** [ipfs/infrastructure#421]
Hopefully this is the right place for this 😟 ...

I'd like to modify the CI pipeline for js-ipfs and js-ipfs-api. The issues I have right now that I'd like to resolve are:

* It takes a long time to be informed of a failure in web worker tests, because they're run sequentially after the nodejs tests and browser tests
* The browser tests and web worker tests are run multiple times on different node versions, but they don't need to be because they are run in the browser and the only thing that needs to change is the OS
* Tests would take less time to complete if nodejs/browser/webworker were performed in parallel

Would like a pipeline like this for example:

MacOS node8
MacOS node10
MacOS browser
MacOS web worker
Linux node8
Linux node10
Linux browser
Linux web worker
Windows node8
Windows node10
Windows browser
Windows web worker

Soon, would like to add:

MacOS service worker
Windows service worker
Linux service worker

**Comment by VictorBjelkholm** [comment]
Moved to https://github.com/ipfs/testing/issues/73
