### ISSUE TITLE
Add HTTPS to arewedistributedyet.com

### ISSUE THREAD

**Issue by lidel** [ipfs/infrastructure#422]
After Dweb Summit multiple people started looking at http://arewedistributedyet.com but it is HTTP-only, which is [bit awkward in Chrome after July](https://blog.cloudflare.com/content/images/2018/02/chrome68.png).

![screenshot_4](https://user-images.githubusercontent.com/157609/43731669-89c7143a-99af-11e8-94cc-a5866f72675a.png)

It is a static page generated from https://github.com/ipfs-shipyard/arewedistributedyet/
A simple Let's Encrypt  should do the trick for getting HTTPS.

cc @olizilla

**Comment by lgierth** [comment]
This is done
