### ISSUE TITLE
DNS for npm-on-ipfs

### ISSUE THREAD

**Issue by achingbrain** [ipfs/infrastructure#427]
A DNS record needs to be created for `registry.ipfs.io` that resolves to the EC2 instance created as part of #423

Please also create a CAA record so I can use letsencrypt to deploy the service using SSL (similar to #298).

**Comment by lgierth** [comment]
Are npm.ipfs.io npm-registry.ipfs.io okay too? (Just worrying that "registry" might be a tad too generic and get in our way in the future.)

**Comment by achingbrain** [comment]
Related issue: https://github.com/ipfs-shipyard/npm-on-ipfs/issues/56

How about `registry.js.ipfs.io`?

**Comment by lgierth** [comment]
The A record is up, CAA todo

**Comment by lgierth** [comment]
I'll defer the CAA record to #298
