### ISSUE TITLE
Deploy IPFS Share Files

### ISSUE THREAD

**Issue by fsdiogo** [ipfs/infrastructure#429]
Hey! 👋 

I've been working on a share files app, [ipfs-shipyard/ipfs-share-files](https://github.com/ipfs-shipyard/ipfs-share-files), and it would be awesome to put that into `share.ipfs.io`.

As this is not production ready it would be in `dev.share.ipfs.io` for now. Check [this PR](https://github.com/ipfs-shipyard/ipfs-share-files/pull/18) for more info.

**Comment by fsdiogo** [comment]
Ping @ipfs/infrastructure!

**Comment by lgierth** [comment]
Hey, sorry about the slow response.

Is this simply a single-page app on IPFS? Then we only need to setup the zone and A/AAAA records, and you can have automatic deploys using the `ci/Jenkinsfile` approach that e.g. PeerPad is using.

**Comment by fsdiogo** [comment]
I'm not really sure what you mean with `a single-page app on IPFS`?

Yes, the idea is to have automatic deploys, I've created [this PR](https://github.com/ipfs-shipyard/ipfs-share-files/pull/18) that should take care of that!

**Comment by lgierth** [comment]
> I'm not really sure what you mean with a single-page app on IPFS?

Does it have a backend, or any server-side components :)

**Comment by fsdiogo** [comment]
Nope 😇

**Comment by lgierth** [comment]
share.ipfs.io and dev.share.ipfs.io are up with hello world content, so the jenkinsfile should work now.

I only need to get a certificate for dev.share.ipfs.io now.

**Comment by lgierth** [comment]
This should be complete now, sorry about the TLS hickup on the last mile :)
