### ISSUE TITLE
Open port range on npm-on-ipfs server

### ISSUE THREAD

**Issue by achingbrain** [ipfs/infrastructure#444]
We have a replication master & a few registry mirrors all running on docker.  Everything's created using `docker-compose` and the mirrors are scaled using the `--scale` argument.

To make installing dependencies faster the ipfs-npm module dials the replication master directly in order to ensure we are connected to the right nodes before using IPFS to pull down dependency tarballs.

This doesn't scale as everyone connects to the master which should be updating it's registry index and not serving files.

I'd like people to connect to the mirrors instead, so could you please open a range of ports that I can use to forward the traffic on to the right docker containers?

10000-10100 would do.

The server is 35.178.192.119 and is in our AWS account somewhere.

Thanks!

**Comment by achingbrain** [comment]
@lgierth @eefahy is there any chance this could get done?  I don't have access to the aws console so can't do it myself.

**Comment by eefahy** [comment]
Done. Also, @achingbrain look for a meeting time with me in the nearish future to chat through this project to see if there are any ways where infra can help out.
