### ISSUE TITLE
Fix dnsimple for explore.ipld.io

### ISSUE THREAD

**Issue by lidel** [ipfs/infrastructure#449]
I noticed that  `/ipns/explore.ipld.io`  and https://explore.ipld.io  were not updated for some time due to dnsimple error:

https://ci.ipfs.team/job/IPFS%20Shipyard/job/ipld-explorer/job/master/4/console:
```
[ipyard_ipld-explorer_master-KNVJNOVICU45J2MBH2J3FIY2FYTWMPVT47THE2IQQPKJPDJECPLA] Running shell script
+ ./dnslink-dnsimple explore.ipld.io /ipfs/QmVDBPHPXiaexukv88rYiBWLvAYRVLH1t9FYJo3YVR12pb _dnslink
error in createRecord: POST https://api.dnsimple.com/v2/zones/explore.ipld.io/records: 404 Not Found
```

cc @olizilla

**Comment by olizilla** [comment]
yep, is a known issue, related https://github.com/ipfs/dev-team-enablement/issues/162

this should be working now, I need to trigger a new build for explore.ipld.io

**Comment by olizilla** [comment]
@VictorBjelkholm same issue for explore.ipld.io as well

**Comment by eefahy** [comment]
This has been fixed, closing. see: https://ci.ipfs.team/job/IPFS%20Shipyard/job/ipld-explorer/job/master/5/console

#454 is staying open for now until a PR and a postmortem has been completed.
