### ISSUE TITLE
Deploy latest ws-star.discovery.libp2p.io updates (0.3.0)

### ISSUE THREAD

**Issue by jacobheun** [ipfs/infrastructure#458]
[ws-star rendezvous @0.3.0](https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/tree/v0.3.0) has been released and needs to be deployed via [dokku](https://github.com/libp2p/js-libp2p-websocket-star-rendezvous/blob/v0.3.0/DEPLOYMENT.md#ipfs-infra).

**Comment by victorb** [comment]
PR pending here: https://github.com/protocol/infra/pull/403

But the deploy already happened! Enjoy much faster discovery! :tada: :tada: :tada:
