### ISSUE TITLE
Things to pin

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#5]
We'll use this issue to track objects to pin for now. I'll add a file. eventually we'll have a much cleaner way to do it.

(let's edit with a checkbox + point to the commit adding the file)

**Comment by jbenet** [comment]
@host add hashes of vms/containers/etc to pin here.

**Comment by hosh** [comment]
From: https://github.com/jbenet/ipfs-container-demos/pull/18/files

/ipfs/QmdiByRvJpAiFp6SKBc38K938NRiYvkUKtSMmETdJjuk6p/ipfs-daemon-0.1.0.tar

**Comment by jbenet** [comment]
From https://github.com/krl/ipfs-geoip/blob/master/ipfs-geoip.js#L3

- [ ] /ipfs/QmQQ3BUpPjgYiTdhp4H9YWSCtoFXs8t91njhpvXNNLd3yB

@krl if you need anything pinned add it to this issue-- i'll get to it.

**Comment by jbenet** [comment]
Brewster's blog:

- [ ] `/ipfs/QmavE42xtK1VovJFVTVkCR5Jdf761QWtxmvak9Zx718TVr`

**Comment by krl** [comment]
Geoip data

[] /ipfs/QmQQ3BUpPjgYiTdhp4H9YWSCtoFXs8t91njhpvXNNLd3yB

**Comment by lgierth** [comment]
Things to pin are now tracked in https://github.com/ipfs/refs-solarnet-storage
