### ISSUE TITLE
Update DNS for dist.ipfs.io

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/infrastructure#502]
Please update the DNS for dist.ipfs.io for pinned hash `QmegiMooj8iM7aMVLRgo9ayvN8imk1WhTnc2ZYyGm1gVzH` (aka https://gateway.ipfs.io/ipfs/QmegiMooj8iM7aMVLRgo9ayvN8imk1WhTnc2ZYyGm1gVzH )

Ref: https://github.com/ipfs/distributions/pull/302

Thanks much!

**Comment by jessicaschilling** [comment]
@mburns Not sure if assigning you to this was the right thing to do. If not, please forgive me 😊

**Comment by mburns** [comment]
```
$ dig +short TXT _dnslink.dist.ipfs.io
"dnslink=/ipfs/QmegiMooj8iM7aMVLRgo9ayvN8imk1WhTnc2ZYyGm1gVzH"
```

**Comment by jessicaschilling** [comment]
@mburns You are a prince among humans. 😊
