### ISSUE TITLE
http://dweb.link shows 404 while https://dweb.link redirects

### ISSUE THREAD

**Issue by Mikaela** [ipfs/infrastructure#503]
I hope this is the right place to report this. On iOS I get the "404 page not found" error screenshotted below and on computer I was surprised that it redirects me to https://docs.ipfs.io/how-to/address-ipfs-on-web/#subdomain-gateway

![404](https://matrix.feneas.org/_matrix/media/r0/download/matrix.feneas.org/7ac973157c90ab93481ffb3c58441dd2f3878e3b)

I have been wondering whom does the domain belong to and while the desktop redirect is better than nothing, I would have hoped there to be a webpage explaining e.g. that dweb.link is an IPFS Subdomain Gatway ran by the IPFS.io team and maybe a link to the [legal page](https://ipfs.io/legal/) which is the most clear mention on who runs it. I am not sure if it's just me, but I don't find [search for dweb.link very explanatory](https://www.ecosia.org/search?q=%22dweb.link%22) and I had to find my way here through [GItHub issue search for dweb.link](https://github.com/issues?q=dweb.link).

**Comment by hsanjuan** [comment]
It seems that http://dweb.link shows 404 while https://dweb.link redirects.

**Comment by Mikaela** [comment]
Thanks, I changed the title appropiately. On desktop I am using Firefox in the HTTPS-only mode enabled in `about:config` and as Firefox iOS doesn't have either `about:config` or extensions, I didn't notice I wasn't using https.

**Comment by thattommyhall** [comment]
This is now deployed 

```
 $ curl -IL http://dweb.link
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 23 Jul 2020 12:00:57 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://dweb.link/
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, Range, Content-Range, X-Chunked-Output, X-Stream-Output
Access-Control-Expose-Headers: Content-Range, X-Chunked-Output, X-Stream-Output
X-IPFS-POP: gateway-bank1-ams1

HTTP/2 307 
server: nginx
date: Thu, 23 Jul 2020 12:00:57 GMT
content-type: text/html
content-length: 180
location: https://docs-beta.ipfs.io/how-to/address-ipfs-on-web/#subdomain-gateway
access-control-allow-origin: *
access-control-allow-methods: GET, POST, OPTIONS
access-control-allow-headers: X-Requested-With, Range, Content-Range, X-Chunked-Output, X-Stream-Output
access-control-expose-headers: Content-Range, X-Chunked-Output, X-Stream-Output
x-ipfs-pop: gateway-bank1-ams1
strict-transport-security: max-age=31536000; includeSubDomains; preload

HTTP/2 301 
server: nginx
date: Thu, 23 Jul 2020 12:00:57 GMT
content-type: text/html
content-length: 178
location: https://docs.ipfs.io/how-to/address-ipfs-on-web/

HTTP/2 200 
server: nginx
date: Thu, 23 Jul 2020 12:00:57 GMT
content-type: text/html
content-length: 49212
vary: Accept-Encoding
accept-ranges: bytes
access-control-allow-methods: GET
etag: "DirIndex-c1aa0601ac3eac2c50b296cf618a6747eeba8579_CID-bafybeiglo7k7uzuixpwcxjccfs5zmbtddhpefxq4m4u7zlfw447gfs6l7e"
last-modified: Thu, 23 Jul 2020 12:00:57 GMT
x-ipfs-gateway-host: collab-cluster-ams1
x-ipfs-path: /ipns/docs.ipfs.io/how-to/address-ipfs-on-web/
access-control-allow-origin: *
access-control-allow-methods: GET, POST, OPTIONS
access-control-allow-headers: X-Requested-With, Range, Content-Range, X-Chunked-Output, X-Stream-Output
access-control-expose-headers: Content-Range, X-Chunked-Output, X-Stream-Output
x-ipfs-pop: collab-cluster-ams1
strict-transport-security: max-age=31536000; includeSubDomains; preload
```
