### ISSUE TITLE
Relaying

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#51]
We can't bust 100 percent of existing NATs, but we can provide opt-in relaying via the bootstrap nodes.

**Comment by jbenet** [comment]
Take a look at https://github.com/ipfs/go-ipfs/issues/57 and https://github.com/ipfs/go-ipfs/tree/bf22aeec/p2p/protocol/relay

I'm thinking
- use other relay nodes (i think default is yes, opt-out).
- allow others to relay _connectivity information only_ -- STUN/TURN/ICE-like. (divided in this, but default yes, opt out would be best for the network).
- allow others to relay arbitrary streams (default no, opt-in).

**Comment by whyrusleeping** [comment]
> allow others to relay connectivity information only -- STUN/TURN/ICE-like. (divided in this, but default yes, opt out would be best for the network).

Dont we already do this throught the DHT?

**Comment by jbenet** [comment]
@whyrusleeping yeah, i'm saying for privacy policies
