### ISSUE TITLE
Rename scruffy and willie

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#58]
We'll stick with the scheme of giant spherish space rocks, in order to not introduce another universe of terms (Matt Groening's janitors, in this case)

- [x] Pick names
- [x] Rename droplets
  - Make sure PTR records were updated
- [x] Migrate DNS from `$janitor.i.ipfs.io` to `$spacerock.i.ipfs.io`
- [x] Update `/etc/hostname` on each host
- [ ] Reconnect Pinbot so that it picks up the new hostname

**Comment by jbenet** [comment]
Some possible names: 

```
phobos, deimos
europa, io, ganymede, callisto
titan, enceladus, rhea, dione, thethys, ...
... luna
```

**Comment by lgierth** [comment]
Taken care of in #67

**Comment by jbenet** [comment]
![](http://gateway.ipfs.io/ipfs/QmRdFePf9KPifkUEsTtpEQt8wtiedVTKD6Ymdii1SUc4Ed/scruffy.png)

![](http://gateway.ipfs.io/ipfs/QmRdFePf9KPifkUEsTtpEQt8wtiedVTKD6Ymdii1SUc4Ed/willie.gif)

**Comment by jbenet** [comment]
(aww... sorry guys)
