### ISSUE TITLE
SSL/TLS Cert for gateway

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#6]

**Comment by thefinn93** [comment]
Bumping, per IRL convo. Suggest using startssl.com for now until Lets Encrypt launches in September. Also [this handy SSL configuration generator](https://mozilla.github.io/server-side-tls/ssl-config-generator/).

**Comment by cryptix** [comment]
I'm with finn on that one. Until the free startssl expires lets encrypt should be rolling.

**Comment by jbenet** [comment]
@lgierth thoughts on best way to tweak our configs for this? maybe we could itemize what we need to do first. I think at least:

- [ ] edit nginx config in this repo to pick up a cert from a file (pickmeup!)
- [ ] get cert (we can pay for one, np, service recs?) (@jbenet)
- [ ] add cert to hosts (@lgierth or @jbenet)
- [ ] deploy it (@lgierth)

**Comment by thefinn93** [comment]
Paying for certs is a scam, use StartSSL for now and use Lets Encrypt in a few months

**Comment by jbenet** [comment]
thanks so much to @lgierth for handling this very important thing

**Comment by cryptix** [comment]
pow(:+1:,:100:)
