### ISSUE TITLE
CORS regression?

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#75]
CORS regression?

![](https://gateway.ipfs.io/ipfs/QmZ1pprJahFME13YwoYADQGeLz3znJtZhhZ5HmYQbi9Upu/cap.png)

**Comment by lgierth** [comment]
Can I have a clickable link? :)

**Comment by jbenet** [comment]
yeah sorry https://gateway.ipfs.io/ipfs/QmVppgFNC8TCJg3zJmSebFtZAJRSw1pS8seuYVstbzEW78/viz#QmTet7b77L78XhYg3zg3N2Md4zA8Zjp3fMsGu3GxSzsyX7

**Comment by jbenet** [comment]
oh i know what's up! https! CORS normally has the protocol too as its part of security. so whatever the output of `ipfs config API.HTTPHeaders` is i bet the cors stuff does not say `https`.

**Comment by lgierth** [comment]
Hrm yeah! https://github.com/ipfs/infrastructure/blob/master/solarnet/roles/ipfs/templates/config.j2#L49-L74

Wanna add https lines and try `./secrets.sh -d ; ansible-playbook gateway.yml`? Otherwise I can do it.

**Comment by lgierth** [comment]
Aaand load the virtualenv first: `. venv/bin/activate ; ./secrets.sh -d ; ansible-playbook gateway.yml`

**Comment by jbenet** [comment]
i totally would but on a reliable network atm. i'll do it for next time. (i'll deploy something later this week anyway, as i want to make sure pinbot has the new `!befriend`

**Comment by lgierth** [comment]
Cool I'll take care of it then
