### ISSUE TITLE
geoip root fails to load in gateway

### ISSUE THREAD

**Issue by harlantwood** [ipfs/infrastructure#79]
Requesting https://ipfs.io/ipfs/QmQQ3BUpPjgYiTdhp4H9YWSCtoFXs8t91njhpvXNNLd3yB

Returns 

> internalWebError: unexpected EOF

Unclear whether this is a go-ipfs issue or nginx etc.

**Comment by lgierth** [comment]
@harlantwood wanna move this to go-ipfs? I reproduced this with a local daemon so it's not an infrastructure issue.

**Comment by jbenet** [comment]
I think this is a non-unixfs merkledag which go-ipfs tries to read as unix-fs. (it shouldn't)
