### ISSUE TITLE
what happened to repo gc?

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#80]
@lgierth `ipfs repo gc` doesnt seem to run on the gateways anymore?

**Comment by jbenet** [comment]
venus' disk is full.

**Comment by jbenet** [comment]
freed some disk space on venus + neptune. they're back on. but all disks are close to full, not sure gc is happening periodically (a grep on `solarnet/` dir reveals nothing). ((i dont think the GC PR is merged yet??))

**Comment by lgierth** [comment]
Oh I though GC was happening automatically? We can certainly do it in a cronjob if neccessary.

**Comment by lgierth** [comment]
The other thing that's filling up the disk is #29

**Comment by lgierth** [comment]
I just gave GC a try on earth and it went from ~31G used down to 8.4G used.

```sh
$ ansible gateway -a 'df -h'
$ ssh root@earth.i.ipfs.io -t docker exec -i -t ipfs ipfs repo gc
```

**Comment by jbenet** [comment]
:+1:

**Comment by lgierth** [comment]
Should deploy ipfs/go-ipfs#1495 once it's landed

**Comment by rht** [comment]
Note: only 1 param out of the three (`GCPeriod`, `StorageGCWatermark`, `StorageMax`) needs to be set.

e.g. if `GCPeriod` is `24h`, measured mean rate is 1GB/hr, max rate is 2GB/hr, pin size 10GB, then `StorageMax` should be 58GB (10 + 24*2), `StorageGCWatermark` should be 58% ((10+24)/58*100).
(this needs to be refined)
