### ISSUE TITLE
Provision resources for hosting OSM

### ISSUE THREAD

**Issue by mikolalysenko** [ipfs/infrastructure#84]
It would be extremely awesome if we could get the whole OSM data set onto IPFS:

http://planet.osm.org/

I am willing to take this on, but I don't have access to the necessary hardware resources to do it yet.  The compressed PBF data set is about 29GB and decompresses to ~0.5TB, which is larger than the disk of any computer I own.

If you guys can hook me up with a computer that has enough extra storage, I'll try to get this thing working on IPFS!

Here is my public key:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYloaaiVByry4lKAfptQZhSYm3VeQju9d6CXHtReLnFn37EB8UJSzxoAxxvYwnzHGgfliF803Ue6Sf6OSi024ojJtTeex6v2ar7RBjF0IqTb0E5D6AsnJ5RA95zBaduOwcdCJci9svglIbF+4Sa69asjks9Qk1MOmjt5HpD5Ra2mhlMXf2h2VS6fzs+fPcsXHRjYa+e9M37Pp9XgeBFWAZu1UplMcTU9WRNEBSstQCa8+CM23kGD4Yd7BaJdLCopoKPzCwvvf2YOm0hLWFTpklJrkOb+Jvz0P5fzDZ/rSom501SVRLVYMSPTn1ZAVp0VQy4wjh7Ap+uH+CID8cYQPl mikolalysenko@gmail.com
```

**Comment by lgierth** [comment]
Yes that sounds great! Do you already have a use case in mind? We don't have unlimited storage at the moment ;)

**Comment by davidar** [comment]
@mikolalysenko I've already done this: ipfs/archives#11

I'm currently working on getting it into a more usable format (vector tiles). I'd really appreciate it if you were able to help with this :)

**Comment by jbenet** [comment]
(for context, i know @mikolalysenko well, and would be awesome if he could help us! :) he pinged me and i told him to post here.)

@davidar that's sweet! i remember the viewer. we should get @mikolalysenko access to `pollux` as well.

**Comment by lgierth** [comment]
Storage nodes access taken care of in #90

**Comment by mikolalysenko** [comment]
Thanks!
