### ISSUE TITLE
IPv6 for gateway and swarm

### ISSUE THREAD

**Issue by lgierth** [ipfs/infrastructure#88]
relevant docker issues: https://github.com/docker/docker/issues/2174 https://github.com/docker/docker/issues/11518 https://github.com/docker/docker/issues/14010
- [x] enable ipv6 for each droplet in an older datacenter
- [ ] give ipfs container an address from the /64 (https://docs.docker.com/engine/userguide/networking/default_network/ipv6/)
- [ ] swarm listens on `/ip6/::/tcp/4001`
- [ ] nginx listens on `/ip6/::/tcp/80` and `/ip6/::/tcp/443`
- [ ] AAAA records for ipfs.io, gateway.ipfs.io, and static pages
- [ ] ipv6 in default bootstrap list

**Comment by ion1** [comment]
It might also be good to have IPv6 addresses in the default bootstrap node list.

**Comment by lgierth** [comment]
Yes good idea, we might also add the fc00::/8 addresses there

**Comment by jbenet** [comment]
Am not sure if the bootstrap list right now would "do the right thing" (import all addresses given for the same peerid into one peerid, and when dialing out only dial one addr per peer)

**Comment by lgierth** [comment]
@whyrusleeping the 6 addresses per node I could come up with for now:

- /ip4/tcp
- /ip4/utp
- /ip6/tcp
- /ip6/utp
- /ip6/tcp with fc00::/8 address
- /ip6/utp with fc00::/8 address
