### ISSUE TITLE
Move off jenkins

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#9]
I've had it with jenkins. it's so painful to work with. I want to move off. It's currently broken-- it isn't building go-ipfs properly.

I really like golang's build system: http://build.golang.org -- it is just https://github.com/golang/build -- ideally we could run our own version of that, equipped with ipfs to avoid re-downloading things multiple times (i.e. so tests get even faster). This sounds non-trivial to setup... 

So perhaps in the meantime we could try to use travis for everything we do in jenkins. This may not work, particularly:
- race tests will crawl or may just fail on travis
- not sure if container tests (`3nodetest`) will work.

The jenkins tests in question are:
- `test_sharness_expensive` ideally with fuse
- `build_docker_image` to check it works
- `build_all_commits` to check all commits build (probably redundant given `test_all_commits)`
- `test_go`
- `test_3node` requires containers
- `test_go_race` likely to be very slow
- `test_all_commits` runs `make test` on all commits.
- `test_go_integration` runs some integration tests

I think that -- instead of only testing `make test` on all commits, we should instead:

- for _every commit_:
  - go test
  - go test race
  - sharness (expensive)
  - build docker image
  - integration tests

This _might_ be as simple as making the repo test all these pieces and using travis.

**Comment by jbenet** [comment]
@whyrusleeping @chriscool thoughts?

**Comment by chriscool** [comment]
First, yeah it is a good idea to test every commit as much as possible, at least as long as it doesn't take too much time.

If Travis works well, it looks like a good idea to do as much as possible using it.

Can FUSE tests be done on Travis too?

As some tests cannot be done on Travis, maybe we can keep Jenkins only for these tests or use something else like http://buildbot.net/.

**Comment by whyrusleeping** [comment]
could take a look at teamcity: https://www.jetbrains.com/teamcity/

**Comment by jbenet** [comment]
i'd prefer a service (that we don't have to manage) and something very
tightly integrated with the open source workflow.

**Comment by jbenet** [comment]
I think we should:
- try to do it all on travis first, have that as something to fallback to always. 
- from there, we can see about circleci and codeship, which both claim to integrate with github + open source well.

**Comment by jbenet** [comment]
closing in favor of https://github.com/ipfs/infrastructure/issues/20
