### ISSUE TITLE
rehost.ipfs.io

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#92]
Would be nice to have a service where you can enter a URL and it would add the content to ipfs and _cache_ it on the gateways. would still need to pin it somewhere, but at least makes it available over ipfs.

**Comment by jbenet** [comment]
bonus points if it works with html pages

**Comment by davidar** [comment]
:+1:

Even better if it uses the same convention as CoralCDN, e.g. http://example.com.ipfs.io/foo/bar.html

Also relevant ipfs/archives#7

**Comment by davidar** [comment]
CC: ipfs/archives#28 @ikreymer

**Comment by lgierth** [comment]
Deferring this to the https://github.com/ipfs/archives repo.
