### ISSUE TITLE
Using Sirius? 

### ISSUE THREAD

**Issue by jbenet** [ipfs/infrastructure#98]
Are we actively using sirius? or is it mostly Pollux? 

cc @davidar @lgierth

**Comment by lgierth** [comment]
They have 17 and 136 GB free:
https://snapshot.raintank.io/dashboard/snapshot/tm79epQmeVbd3ZaVu8c7p5Vi6BhoYmv1

pollux = fce5:18b5:e3c6:ad87:465d:c4f7:ac7f:6aad
sirius = fc66:9d5a:41e:6b7d:180e:ecdb:12e5:e9d5

**Comment by lgierth** [comment]
Maybe worth running `ipfs repo gc` there on the per-person daemons

**Comment by davidar** [comment]
@jbenet yes, I'm using both :)
